### ISSUE TITLE
Update a conda env yaml file (not the env itself)

### ISSUE THREAD

**Issue by hadim** [conda/conda#10008]
I have the following env file:

```yaml
channels:
  - conda-forge
  - pytorch
  - anaconda

dependencies:
    # Python
    - python==3.7.6
    - pip==20.0.2
    - requests==2.22.0
    - importlib_resources==1.0.2
    - pyyaml==5.3.1
    - tqdm==4.46.0

    # Test and formating
    - pytest==5.4.1
    - black==19.10b0
    - coverage==5.0.3
    - pytest-cov==2.8.1

    # Scientific
    - numpy==1.18.4
    - matplotlib==3.2.1
    - scipy==1.4.1
    - sparse==0.9.1
    - pandas==1.0.3
    - statsmodels==0.11.1
    - scikit-learn==0.23.0
    - xlrd==1.2.0

    # Plotting
    - bokeh==2.0.1
    - seaborn==0.10.0

    # Misc
    - graphviz==2.42.3
    - versioneer==0.18
    - awscli==1.18.62
    - python-wget==3.2
    - click==7.1.2
    - imageio==2.8.0
    - fabric==2.5.0

    # Jupyter
    - ipywidgets==7.5.1
    - jupyterlab==2.1.4

    # Configuration
    - omegaconf==2.0.0

    # Chemistry
    - rdkit==2020.03.2
    - openbabel==3.0.0
    - oddt==0.7
    - pubchempy==1.0.4
    - mordred==1.2.0
    - nglview==2.7.5
    - molvs=0.1.1
    - qvina==2.1.0
    - mdtraj==1.9.3
    - ase==3.19.1

    # GPU
    - anaconda::cudatoolkit==10.1.243
    - gpustat==0.6.0
    - pynvml==8.0.4

    # PyTorch
    - pytorch::pytorch==1.5.0
    - pytorch::torchvision==0.6.0
    - pytorch-lightning==0.7.6

    # Tensorflow/Tensorboard
    - anaconda::tensorboard==2.2.1
    - anaconda::tensorflow==2.2.0
```

I am looking for a way to update this env file.

The current way I do it is to run `conda update --all`, look for the packages in my env file and bump manually the version number.

How could I do that automatically? I tried to look at the conda API but this is not straightforward what the different steps should be.

I think I need to programmatically run `conda update --all` and also load a Python model specification of the env (the env YAML file) and match the package that should be updated.

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-75)
