### ISSUE TITLE
Passing options to pip installer

### ISSUE THREAD

**Issue by sstallion** [conda/conda#10119]
In our environment.yml we have a large set of pip requirements that are normally installed in two phases; the first phase is via a frozen requirements.txt and the second is for a batch of local editable packages. One of the issues we've encountered is that we normally pass `--no-deps` to pip when installing the editable packages, however since conda generates a requirements file, this is no longer possible due to limitations within pip.

I've modified the pip installer to allow passing command line arguments to pip, however this comes with a couple of caveats:

1. The naive approach creates multiple pip invocations, by removing the intermediary requirements file, which may not be ideal for those who don't make use of requirements files in their environments:

```
dependencies:
  - pip
  - pip:
    - -r requirements.txt
    - --no-deps -e some/local/path1
    - --no-deps -e some/local/path2
      :
```

1. It seems to be possible (though not documented) to have multiple pip installers invoked by env.py, it could be possible to add pip options in a way that is backwards compatible, however it would require more invasive changes due to pip dependencies no longer being treated as a simple list:

```
dependencies:
  - pip
  - pip:
    - -r requirements.txt # preserve original behavior
  - pip:
    options: --no-deps    # new behavior (detected via dict vs. list)
    requirements:
      - -e some/local/path1
      - -e some/local/path2
        :
```

I'm happy to do the legwork for this in either case, but I'd like for the resulting work to be mergeable upstream. Are there any strong opinions on which approach is better?
