### ISSUE TITLE
Cannot specify version number for one package among many even though, left unspecified, it installs the version number I am trying to specify

### ISSUE THREAD

**Issue by dumbledad** [conda/conda#10168]
**I'm submitting a...**

- [x] bug report
- [ ] feature request

## Current Behavior
Amidst a long list of fully specified conda python packages in a YAML file

- `sqlite` works and conda installs version 3.23.3
- `sqlite==3.23.3` fails with the error _ResolvePackageNotFound: sqlite==3.23.3_
- `sqlite==3.23.*` fails with huge error message starting _Found conflicts_

### Steps to Reproduce
I have the following YAML file to create a conda environment.
```
    name: test1
    channels:
      - defaults
      - pytorch
      - conda-forge
    dependencies:
      - coverage==5.0
      - cudatoolkit==10.2.89
      - dataclasses==0.7
      - future==0.18.2
      - joblib==0.16.0
      - jupyter==1.0.0
      - keyring==21.2.1
      - matplotlib==3.2.2
      - mypy==0.782
      - numpy==1.19.1
      - pandas==0.25.3
      - param==1.9.2
      - pip==20.2.2
      - pylint==2.5.3
      - python==3.8.5
      - python-dateutil==2.8.1
      - pytorch==1.6.0
      - pyyaml==5.3.1
      - scikit-learn==0.23.1
      - scipy==1.5.0
      - seaborn==0.10.1
      - sqlite
      - tensorboard==2.2.1
      - torchvision==0.7.0
      - visdom==0.1.8.9
```

It works fine. When I activate the environment and check the package versions I find that the only package I did not specify a version number for (`sqlite`) it has been found as 

```
    > Name     Version   Build        Channel  
    > sqlite   3.32.3    h2a8f88b_0  
```

But if I try to peg sqlite to that version number it fails. For example this config file

```
    name: test2
    channels:
      - defaults
      - pytorch
      - conda-forge
    dependencies:
      - coverage==5.0
      - cudatoolkit==10.2.89
      - dataclasses==0.7
      - future==0.18.2
      - joblib==0.16.0
      - jupyter==1.0.0
      - keyring==21.2.1
      - matplotlib==3.2.2
      - mypy==0.782
      - numpy==1.19.1
      - pandas==0.25.3
      - param==1.9.2
      - pip==20.2.2
      - pylint==2.5.3
      - python==3.8.5
      - python-dateutil==2.8.1
      - pytorch==1.6.0
      - pyyaml==5.3.1
      - scikit-learn==0.23.1
      - scipy==1.5.0
      - seaborn==0.10.1
      - sqlite==3.23.3
      - tensorboard==2.2.1
      - torchvision==0.7.0
      - visdom==0.1.8.9
```

gives the error 

```
    > ResolvePackageNotFound:
    >   - sqlite==3.23.3
```

while this config file

```
    name: test3
    channels:
      - defaults
      - pytorch
      - conda-forge
    dependencies:
      - coverage==5.0
      - cudatoolkit==10.2.89
      - dataclasses==0.7
      - future==0.18.2
      - joblib==0.16.0
      - jupyter==1.0.0
      - keyring==21.2.1
      - matplotlib==3.2.2
      - mypy==0.782
      - numpy==1.19.1
      - pandas==0.25.3
      - param==1.9.2
      - pip==20.2.2
      - pylint==2.5.3
      - python==3.8.5
      - python-dateutil==2.8.1
      - pytorch==1.6.0
      - pyyaml==5.3.1
      - scikit-learn==0.23.1
      - scipy==1.5.0
      - seaborn==0.10.1
      - sqlite==3.23.*
      - tensorboard==2.2.1
      - torchvision==0.7.0
      - visdom==0.1.8.9
```

gives a 371 line error message starting

```
    > Found conflicts! Looking for incompatible packages.
```

## Expected Behavior
I should be able to specify the version of sqlite package using either `sqlite==3.23.3` or `sqlite==3.23.*`

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : test1
    active env location : C:\Users\timregan\Miniconda3\envs\test1
            shell level : 3
       user config file : C:\Users\timregan\.condarc
 populated config files :
          conda version : 4.8.4
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages :
       base environment : C:\Users\timregan\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\timregan\Miniconda3\pkgs
                          C:\Users\timregan\.conda\pkgs
                          C:\Users\timregan\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\timregan\Miniconda3\envs
                          C:\Users\timregan\.conda\envs
                          C:\Users\timregan\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.8.3 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
(Empty response from conda config --show-sources)
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at C:\Users\timregan\Miniconda3\envs\test1:
#
# Name                    Version                   Build  Channel
_pytorch_select           0.1                       cpu_0    defaults
absl-py                   0.9.0                    py38_0    defaults
argon2-cffi               20.1.0           py38he774522_1    defaults
astroid                   2.4.2                    py38_0    defaults
attrs                     19.3.0                     py_0    defaults
backcall                  0.2.0                      py_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.5                      py_0    defaults
blinker                   1.4                      py38_0    defaults
brotlipy                  0.7.0           py38he774522_1000    defaults
ca-certificates           2020.6.24                     0    defaults
cachetools                4.1.1                      py_0    defaults
certifi                   2020.6.20                py38_0    defaults
cffi                      1.14.0           py38h7a1dbc1_0    defaults
chardet                   3.0.4                 py38_1003    defaults
click                     7.1.2                      py_0    defaults
colorama                  0.4.3                      py_0    defaults
coverage                  5.0              py38he774522_0    defaults
cryptography              2.9.2            py38h7a1dbc1_0    defaults
cudatoolkit               10.2.89              h74a9793_1    defaults
cycler                    0.10.0                   py38_0    defaults
dataclasses               0.7                      py38_0    defaults
decorator                 4.4.2                      py_0    defaults
defusedxml                0.6.0                      py_0    defaults
entrypoints               0.3                      py38_0    defaults
freetype                  2.10.2               hd328e21_0    defaults
future                    0.18.2                   py38_1    defaults
google-auth               1.20.1                     py_0    defaults
google-auth-oauthlib      0.4.1                      py_2    defaults
grpcio                    1.31.0           py38he7da953_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 ha925a31_3    defaults
idna                      2.10                       py_0    defaults
importlib-metadata        1.7.0                    py38_0    defaults
importlib_metadata        1.7.0                         0    defaults
intel-openmp              2019.4                      245    defaults
ipykernel                 5.3.4            py38h5ca1d4c_0    defaults
ipython                   7.16.1           py38h5ca1d4c_0    defaults
ipython_genutils          0.2.0                    py38_0    defaults
ipywidgets                7.5.1                      py_0    defaults
isort                     4.3.21                   py38_0    defaults
jedi                      0.17.0                   py38_0    defaults
jinja2                    2.11.2                     py_0    defaults
joblib                    0.16.0                     py_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                3.2.0                    py38_0    defaults
jupyter                   1.0.0                    py38_7    defaults
jupyter_client            6.1.6                      py_0    defaults
jupyter_console           6.1.0                      py_0    defaults
jupyter_core              4.6.3                    py38_0    defaults
keyring                   21.2.1                   py38_0    defaults
kiwisolver                1.2.0            py38h74a9793_0    defaults
lazy-object-proxy         1.4.3            py38he774522_0    defaults
libmklml                  2019.0.5                      0    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libprotobuf               3.12.4               h200bbdf_0    defaults
libsodium                 1.0.18               h62dcd97_0    defaults
libtiff                   4.1.0                h56a325e_1    defaults
lz4-c                     1.9.2                h62dcd97_1    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markdown                  3.2.2                    py38_0    defaults
markupsafe                1.1.1            py38he774522_0    defaults
matplotlib                3.2.2                         0    defaults
matplotlib-base           3.2.2            py38h64f37c6_0    defaults
mccabe                    0.6.1                    py38_1    defaults
mistune                   0.8.4           py38he774522_1000    defaults
mkl                       2019.4                      245    defaults
mkl-service               2.3.0            py38hb782905_0    defaults
mkl_fft                   1.1.0            py38h45dec08_0    defaults
mkl_random                1.1.0            py38hf9181ef_0    defaults
msys2-conda-epoch         20160418                      1    defaults
mypy                      0.782                      py_0    defaults
mypy_extensions           0.4.3                    py38_0    defaults
nbconvert                 5.6.1                    py38_0    defaults
nbformat                  5.0.7                      py_0    defaults
ninja                     1.10.0           py38h7ef1ec2_0    defaults
notebook                  6.1.1                    py38_0    defaults
numpy                     1.19.1           py38h5510c5b_0    defaults
numpy-base                1.19.1           py38ha3acd2a_0    defaults
oauthlib                  3.1.0                      py_0    defaults
olefile                   0.46                       py_0    defaults
openssl                   1.1.1g               he774522_1    defaults
packaging                 20.4                       py_0    defaults
pandas                    0.25.3           py38ha925a31_0    defaults
pandoc                    2.10.1                        0    defaults
pandocfilters             1.4.2                    py38_1    defaults
param                     1.9.2                      py_0    defaults
parso                     0.8.0                      py_0    defaults
pickleshare               0.7.5                 py38_1000    defaults
pillow                    7.2.0            py38hcc1f983_0    defaults
pip                       20.2.2                   py38_0    defaults
prometheus_client         0.8.0                      py_0    defaults
prompt-toolkit            3.0.5                      py_0    defaults
prompt_toolkit            3.0.5                         0    defaults
protobuf                  3.12.4           py38ha925a31_0    defaults
psutil                    5.7.0            py38he774522_0    defaults
pyasn1                    0.4.8                      py_0    defaults
pyasn1-modules            0.2.7                      py_0    defaults
pycparser                 2.20                       py_2    defaults
pygments                  2.6.1                      py_0    defaults
pyjwt                     1.7.1                    py38_0    defaults
pylint                    2.5.3                    py38_0    defaults
pyopenssl                 19.1.0                     py_1    defaults
pyparsing                 2.4.7                      py_0    defaults
pyqt                      5.9.2            py38ha925a31_4    defaults
pyrsistent                0.16.0           py38he774522_0    defaults
pysocks                   1.7.1                    py38_0    defaults
python                    3.8.5                he1778fa_0    defaults
python-dateutil           2.8.1                      py_0    defaults
pytorch                   1.6.0           cpu_py38h538a6d7_0    defaults
pytz                      2020.1                     py_0    defaults
pywin32                   227              py38he774522_1    defaults
pywin32-ctypes            0.2.0                 py38_1000    defaults
pywinpty                  0.5.7                    py38_0    defaults
pyyaml                    5.3.1            py38he774522_1    defaults
pyzmq                     19.0.1           py38ha925a31_1    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtconsole                 4.7.5                      py_0    defaults
qtpy                      1.9.0                      py_0    defaults
requests                  2.24.0                     py_0    defaults
requests-oauthlib         1.3.0                      py_0    defaults
rsa                       4.6                        py_0    defaults
scikit-learn              0.23.1           py38h25d0782_0    defaults
scipy                     1.5.0            py38h9439919_0    defaults
seaborn                   0.10.1                     py_0    defaults
send2trash                1.5.0                    py38_0    defaults
setuptools                49.6.0                   py38_0    defaults
sip                       4.19.13          py38ha925a31_0    defaults
six                       1.15.0                     py_0    defaults
sqlite                    3.32.3               h2a8f88b_0    defaults
tensorboard               2.2.1              pyh532a8cf_0    defaults
tensorboard-plugin-wit    1.6.0                      py_0    defaults
terminado                 0.8.3                    py38_0    defaults
testpath                  0.4.4                      py_0    defaults
threadpoolctl             2.1.0              pyh5ca1d4c_0    defaults
tk                        8.6.10               he774522_0    defaults
toml                      0.10.1                     py_0    defaults
torchfile                 0.1.0                      py_0    conda-forge
torchvision               0.7.0                py38_cu102    pytorch
tornado                   6.0.4            py38he774522_1    defaults
traitlets                 4.3.3                    py38_0    defaults
typed-ast                 1.4.1            py38he774522_0    defaults
typing_extensions         3.7.4.2                    py_0    defaults
urllib3                   1.25.10                    py_0    defaults
vc                        14.1                 h0510ff6_4    defaults
visdom                    0.1.8.9                       0    conda-forge
vs2015_runtime            14.16.27012          hf0eaf9b_3    defaults
wcwidth                   0.2.5                      py_0    defaults
webencodings              0.5.1                    py38_1    defaults
websocket-client          0.57.0                   py38_1    defaults
werkzeug                  1.0.1                      py_0    defaults
wheel                     0.34.2                   py38_0    defaults
widgetsnbextension        3.5.1                    py38_0    defaults
win_inet_pton             1.1.0                    py38_0    defaults
wincertstore              0.2                      py38_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.11.2           py38he774522_0    defaults
xz                        5.2.5                h62dcd97_0    defaults
yaml                      0.2.5                he774522_0    defaults
zeromq                    4.3.2                ha925a31_2    defaults
zipp                      3.1.0                      py_0    defaults
zlib                      1.2.11               h62dcd97_4    defaults
zstd                      1.4.5                h04227a9_0    defaults
```
</p></details>
