### ISSUE TITLE
Detect available environments (e.g. for CI cache)

### ISSUE THREAD

**Issue by christian-steinmeyer** [conda/conda#10191]
## Motivation

In my project, I use conda as depency manager. I recently added continuous integration (via gitlab ci/cd) to the project and use multiple jobs in several stages. For the sake of simplicity, let's say I have a build job and a test job. I am using the `continuumio/miniconda3:latest` image. Currently, what I do in any job is create the conda environment from the `environment.yml` and then do the actual work. This adds an overhead of several minutes to any job. I already cache the conda packages like so:

```yml
variables:
  CONDA_PKGS_DIRS: "${CI_PROJECT_DIR}/.cache/conda/pkgs"
cache:
  paths:
    - ".cache/conda/pkgs"
```

And this already increased the job's speed. However, what I would like to do is cache the environment like so:

```yml
variables:
  CONDA_ENVS_DIRS: "${CI_PROJECT_DIR}/.cache/conda/envs"
cache:
  paths:
    - ".cache/conda/envs"
```
That way, I could create the environment once in my first execution of the build job and then use it directly from all other jobs, assuming conda could find existing environments at a given path and simply register them. Note that this currently doesn't work with my above approach, because while the gitlab cache does include the environment repository, each job gets executed independent of the others meaning while they are supplied with the cache, running `conda info --envs` yields only the base environment (because the project environment was never initialized / registered for this instance of conda). I did research ways to solve this issue, but could not find any solution. If you know one, please let me know, otherwise perhaps you could consider the following suggestion.

## Suggestion
Add a command like `conda env register path/to/directory` (or `conda env find path/to/directory`).

Expected behavior: Conda scans this directory for existing conda environments and registers it with the current conda instance, so that it can be activated and listed through `conda info --envs` from now on. Ideally, it would also to a sanity or integrity check.

---
Disclaimer: I understand that outside the scope of CI, this use case might not be in line with the intention behind conda. However, I believe that with CI gaining ever more importance, this could be a real benefit.
