### ISSUE TITLE
Parameterized an env.yml file during conda env creation

### ISSUE THREAD

**Issue by hadim** [conda/conda#10398]
Consider the following env file:

```yaml
name: my-env

channels:
  - conda-forge
  - anaconda

dependencies:
  - python >=3.6
  - pip
  - matplotlib
  - pandas >=1.0
  - rdkit
  - click
  - loguru
  - omegaconf >=2.0.0
  - tqdm
  - ipywidgets
  - appdirs
```

This my "base" conda env that is versioned in a GH repo and the dev can use it to set up their dev env developing the library.

The constraints are "soft by-design" so we can locally quickly detect when the "latest" version of a dep is not compatible with the lib.

But during CI or the build of a docker image, we might want to specify some constraint over important dependencies. For example, it's standard to test multiple python versions during CI or build with different versions of cudatoolkit during the build of a docker image.

I am looking for a simple way to specify those constraints during the conda env creation without having to deal with multiple env files.

I was thinking of something like that:

```bash
mamba create -n my-env
mamba env update -f env.yml --constraints "python=3.7"
```

But maybe there is already a way to do something similar?

Note: I could also use a tool such as `yq` to edit on-the-fly the env file but `yq` is not always available and I would prefer not have to rely on yet-another-tool.
