### ISSUE TITLE
Symlinked file-based channels considered distinct

### ISSUE THREAD

**Issue by chebee7i** [conda/conda#10418]
Hi, I have a directory which is listed as a channel like so: `file:///another/path/some_folder`.  When I install from a yaml file, conda gives a warning like:

```console
Warning: 2 possible package resolutions (only showing differing packages):                             
  - file:///other/path/some_folder/linux-64::conda-build-3.20.5-py38_0
  - file:///path/to/cvmfs/some_folder/inux-64::conda-build-3.20.5-py38_0

```

These are acutally the same paths because `some_folder` is a symlink pointing to the cmvfs folder.

```console
$ ls -la /other/path/
total 20                                                            
drwxr-x---  3 user group  4096 Dec 16 01:42 .                      
drwxr-x--- 28 user group  4096 Dec 16 01:29 ..                     
-rw-r-----  1 user group   200 Dec 16 01:42 some_folder -> /path/to/cvmfs/some_folder
```

If I export a yaml file from an environment, the channel is listed twice as well:

```
 name: null                                                
 channels:                                                 
   - file:///other/path/some_folder
   - conda-forge                                           
   - defaults                                              
   - file:///path/to/cvmfs/some_folder
 dependencies:                                             
     ...
```

So `conda` seems to get a little confused here.  There should be no warnings here and the channel should not be repeated.
