### ISSUE TITLE
[Question] prefix field in exported yml file

### ISSUE THREAD

**Issue by tashrifbillah** [conda/conda#10466]
Hi all,

[This](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#exporting-an-environment-file-across-platforms) example shows:

```yml
(env-name) ➜  ~ conda env export --from-history
name: env-name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - codecov
prefix: /Users/username/anaconda3/envs/env-name
```

If I email this to a user, how would the `prefix` field work for them? They may not have such a directory structure in their machine. I guess my confusion is, whether the `prefix` field would be useful at all in a different machine.
