### ISSUE TITLE
Enable automatic "development mode" in env export and env create

### ISSUE THREAD

**Issue by jaksiprejak** [conda/conda#10598]
### I'm submitting a...
* [ ] bug report
* [x] feature request

### Example of desired behaviour
Instead of a workflow like this:

1.  conda env export > environment.yml
1.  conda env create -n myenv -f environment.yml
1.  conda activate myenv
1. conda develop /path/to/my/repo

It would be more efficient to have something like this:

1. conda env export --develop-path=/path/to/my/repo
1. conda env create -n myenv -f environment.yml

**Comment by sntgluca** [comment]
To add to this request:

It would be great if there was a session in environment.yml where we could include a list of additional paths, which would be run via conda-develop in the backend, similarly to what can be done with conda-config.

Something like this:
```yaml
name: myenv
...
develop:
    - /path/to/my/repo
    - /path/to/another/library
 variables:
    VAR1: var
```
