### ISSUE TITLE
Revision rollback does not update specs

### ISSUE THREAD

**Issue by mfansler** [conda/conda#10693]
## Current Behavior

Rolling back a revision fails to properly update the specifications in the `conda-meta/history` file. This results in decoherence between `conda env export` and `conda env export --from-history`. This could potentially lead to reversion to the state upon later updating of the environment.

### Steps to Reproduce

```bash
# create environment with zlib
conda create -n foo libcxx=10

# install newer version of zlib
conda install -n foo libcxx=11

# revert
conda install -n foo --revision 0

## Note the output in package plan:
## Package Plan ##

##  environment location: /Users/mfansler/miniconda3/envs/foo

##  added / updated specs:
##    - libcxx=11

## The following packages will be DOWNGRADED:

##  libcxx                                  11.1.0-habf9029_0 --> 10.0.1-h5f48129_0
```

### Full YAML Ouput
```
conda env export -n foo
```

```yaml
name: foo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - libcxx=10.0.1=h5f48129_0
prefix: /Users/mfansler/miniconda3/envs/foo
```

### Explicit Specifications YAML
```bash
conda env export -n foo --from-history
```

```yaml
name: foo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - libcxx=11
prefix: /Users/mfansler/miniconda3/envs/foo
```

## Expected Behavior

Explicit specifications should be updated correctly. The command with `--from-history` should show:

```yaml
name: foo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - libcxx=10
prefix: /Users/mfansler/miniconda3/envs/foo
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : /Users/mfansler/miniconda3
            shell level : 1
       user config file : /Users/mfansler/.condarc
 populated config files : /Users/mfansler/miniconda3/.condarc
                          /Users/mfansler/.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.7.10.final.0
       virtual packages : __osx=10.14.6=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/mfansler/miniconda3  (writable)
      conda av data dir : /Users/mfansler/miniconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/mfansler/miniconda3/pkgs
                          /Users/mfansler/.conda/pkgs
       envs directories : /Users/mfansler/miniconda3/envs
                          /Users/mfansler/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.7.10 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</p></details>
