### ISSUE TITLE
Feature request: Add support for CRAN in environment.yaml similar to support for pip

### ISSUE THREAD

**Issue by kaedonkers** [conda/conda#10708]
## Background
I really like and have a lot of experience with using conda for defining reproducible environments in Python projects.
The `environment.yaml` syntax is easy to use and rich in functionality. 
I like the ability to pin package versions and especially like the integration of `pip` for installing packages straight from PyPI. 
For example:

```yaml
name: my-env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - pandas=1.0.1
  - pip:
    - matplotlib
```

This is easy to use and "just works".

## Problem
Now I'm working with R a lot more and wish to define reproducible environments using `conda` that support both Python and R.

I am aware that there is a conda channel specifically for [R packages](https://anaconda.org/r/repo), but this channel is not as comprehensive as [CRAN](https://cran.r-project.org/). Infact, I see CRAN as a canonical source of packages for the R language, in a similar way that PyPI is a canonical source of packages for Python packages.

I am also aware that [`conda-build`](https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-r-pkgs.html) can be used to install packages from CRAN using the following steps:

```bash
conda install conda-build
conda skeleton cran <CRAN package name>
conda build r-<CRAN package name>
conda install --use-local r-<CRAN package name>
```

This is very manual, compared to the `pip` example above, and if I have a lot of specific R packages to install it gets tedious.

## Feature request
Therefore, I am requesting that, in a similar way to the `pip` support in the example `environment.yaml` above, CRAN (and other non-Python package sources)[1] be integrated into `conda` using the features available in [`conda-build`](https://docs.conda.io/projects/conda-build/en/master/user-guide/tutorials/build-r-pkgs.html).
An example of how a resulting `environment.yaml` would look:

```yaml
name: my-env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - conda-build
  - numpy
  - pandas=1.0.1
  - pip:
    - matplotlib
  - cran:
    - tidyr
```

This would ensure that users of `conda` could access canonical R packages without relying on Anaconda supporting said packages in the `r` conda channel.

This is reflected in the comment by Mathemilda on https://github.com/conda/conda/issues/10661#issuecomment-843513576, highlighting the need for sometimes obscure R packages that are available on CRAN but aren't the "top 6000" supported by Anaconda.

- - -
[1] [Other package](https://docs.conda.io/projects/conda-build/en/master/resources/commands/conda-skeleton.html) sources supported by `conda-build` include:

* [cpan](https://www.cpan.org/) (Perl)
* [luarocks](https://luarocks.org/) (Lua)
* [rpm](http://rpm.org/) (Linux)
