### ISSUE TITLE
Conda does not install dependencies from meta.yaml when creating a custom package

### ISSUE THREAD

**Issue by UsmanMaan324** [conda/conda#11056]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

I've a pip package and want to create a conda package of that same pacakge as well. Most of the packages are not available on official anaconda so gonna create from conda-forge.
The build goes successful by this command
`conda build . -c conda-forge`
This is what my conda build generates
**meta.yaml file**
```
build:
  noarch: generic
  number: "{{ build_number }}"
  string: "{{ version }}"

requirements:
  run:
    - python
    - 'pandas>=1.3.2'
    - 'sqlalchemy>=1.4.19'
    - 'snowflake-sqlalchemy==1.3.1'
    - 'cryptography==3.3.2'
    - 'snowflake-connector-python==2.6.2'
    - 'numpy>=1.18.1'
    - 'dash==1.21.0'
    - 'dash-core-components==1.17.1'
    - 'dash-html-components==1.1.4'
    - 'dash-bootstrap-components==0.13.0'
    - 'dash-table==4.12.0'
    - 'pyarrow==5.0.0'
    - 'pyyaml>=5.4.1'
    - 'certifi==2020.12.5'
    - 'pyodbc==4.0.31'
    - 'jupyter==1.0.0'
    - 'jupyter-dash==0.4.0'

# test:
 #   imports:
 #     - mdodata

about:
  home: https://mypackage.com
  summary: This is the python version of the my-package library
  license: Proprietary
```
This is what my conda build generates
mypackage-2.0-2.0.tar.tz2/
```
├── info/
│   ├── recipe
|   ├── about.json
|   ├── files
|   ├── git
|   ├── hash_input.json
|   ├── index.json
|   ├── paths.json
├── site-packages/
│   ├── mypackage
|   ├── mypackage-2021.10-py3.6.egg-info
```
The index file contain all the dependencies in depends tag that I mentioned in meta.yaml file.
**index.json**
```
{
  "arch": null,
  "build": "2.0",
  "build_number": 3,
  "depends": [
    "certifi 2020.12.5",
    "cryptography 3.3.2",
    "dash 1.21.0",
    "dash-bootstrap-components 0.13.0",
    "dash-core-components 1.17.1",
    "dash-html-components 1.1.4",
    "dash-table 4.12.0",
    "jupyter 1.0.0",
    "jupyter-dash 0.4.0",
    "numpy >=1.18.1",
    "pandas >=1.3.2",
    "pyarrow 5.0.0",
    "pyodbc 4.0.31",
    "python",
    "pyyaml >=5.4.1",
    "snowflake-connector-python 2.6.2",
    "snowflake-sqlalchemy 1.3.1",
    "sqlalchemy >=1.4.19"
  ],
  "license": "Proprietary",
  "name": "mypackage",
  "noarch": "generic",
  "platform": null,
  "subdir": "noarch",
  "timestamp": 1637563872943,
  "version": "2.0"
}
```
When I install the package, it only install or copy the source code. It do not install all the dependencies that I mentioned it meta.yaml file under requirements. For example when I import the package in python it says that `pandas` could not be found

I install the package through the command that is given below.

`conda install --use-local mypackage-2.0-2.0.tar.tz2`

### Conda info

```shell
active environment : c_i_mdo_py36
    active env location : /home/usman/miniconda3/envs/c_i_mdo_py36
            shell level : 1
       user config file : /home/usman/.condarc
 populated config files : /home/usman/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.8.10.final.0
       virtual packages : __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/usman/miniconda3  (writable)
      conda av data dir : /home/usman/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /tmp/temp_conda_recipe
       envs directories : /home/usman/miniconda3/envs
                          /home/usman/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.8.10 Linux/5.4.0-26-generic ubuntu/20.04 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Conda config

```shell
==> /home/usman/.condarc <==
auto_activate_base: False
pkgs_dirs:
  - /tmp/temp_conda_recipe
channels:
  - conda-forge
  - defaults
```

### Conda list

```shell
# packages in environment at /home/usman/miniconda3/envs/c_i_mdo_py36:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2016.9.26                py36_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
mdodata                   2.0                         2.0    file:///home/usman/miniconda3/envs/c_mdo_py36/conda-bld
ncurses                   6.2                  h58526e2_4    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
python                    3.6.13          hb7a2778_2_cpython    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                49.6.0           py36h5fab9bb_3    conda-forge
sqlite                    3.36.0               h9cd32fc_2    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
```
