### ISSUE TITLE
Optional dependencies in environment file

### ISSUE THREAD

**Issue by HealthyPear** [conda/conda#12098]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Define and install optional dependencies from an environment file (apologies if this is already possible, but I couldn't do it)

### Why is this needed?

It should resemble what is possible in setuptools

### What should happen?

A conda recipe defined by a file `environment.yaml` would look something like

```yaml
name : my_env
channels:
 - conda-forge
dependencies:
 - A
 - B
 - pip
 - pip:
    - G
optional_dependencies
    C:
      - C
    other:
      - D
      - E
      pip:
      - F
    seaborn:
      - seaborn
    all:
      - C
      - other
```

and then the installation command should accept a similar syntax to `pip`, namely

- `conda install -f environment.yaml` would install only (required) `dependencies`
- `conda install -f environment.yaml[C]` would install (required) `dependencies` + `C`
- `conda install -f environment.yaml[C, seaborn]` would install (required) `dependencies` + `C` + `seaborn`, but not `other`
- `conda install -f environment.yaml[all]` would install (required) `dependencies` + all optional depedencies

Not sure what would be the best syntax for the installation command, this is just an example.
Also, the `all` keyword might be also implicit.
