### ISSUE TITLE
Specify a channel in which to search for dependencies during build

### ISSUE THREAD

**Issue by jrsmith3** [conda/conda#1225]
I am trying to integrate travis-ci with a [project on which I'm working](http://github.com/jrsmith3/ibei/). Travis-ci is failing at the build step of the package with the [error](https://travis-ci.org/jrsmith3/ibei/jobs/55853116#L684)

```
$ conda build -c jrsmith3 conda.recipe
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
Removing old build directory
Removing old work directory
BUILD START: ibei--np19py27_0
Fetching package metadata: ........
Error: No packages found in current linux-64 channels matching: physicalproperty
The command "conda build -c jrsmith3 conda.recipe" failed and exited with 1 during .
Your build has been stopped.
```

I think the problem is that one of the dependencies of the package under test is only available from my binstar channel. As you can see in the snippet above, I'm calling the build command with the "-c jrsmith3" flag, so I think `conda` should be searching my binstar channel for dependencies.

I don't understand why travis-ci can't build my package. Is there anything I am missing?

[`.travis.yml`](https://github.com/jrsmith3/ibei/blob/cd68b9d47c1770cc9840dafae9618b25b9d1c41b/.travis.yml):

```yaml
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - sudo apt-get update
  # You may want to periodically update this, although the conda update
  # conda line below will keep everything up-to-date.  We do this
  # conditionally because it saves us some downloading if the version is
  # the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-build
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION anaconda
  - source activate test-environment
  - conda build -c jrsmith3 conda.recipe
  - conda install ibei --use-local

script: nosetests
```

The package's [`meta.yaml`](https://github.com/jrsmith3/ibei/blob/cd68b9d47c1770cc9840dafae9618b25b9d1c41b/conda.recipe/meta.yaml):

```yaml
package:
    name: ibei
    # version: x.y.z
    # The version string is stored in `ibei/version.py`.
    # `build.sh` includes code to properly incorporate the version
    # string in the built package.

source:
    path: ..

requirements:
    build:
        - python
        - numpy
        - astropy
        - sympy
        - physicalproperty
    run:
        - python
        - numpy
        - astropy
        - sympy
        - physicalproperty

test:
    files:
        - ../test/test_DeVosSolarcell.py
        - ../test/test_SBSolarcell.py
        - ../test/test_uiebi.py
    requires:
        - nose

about:
    home: https://github.com/jrsmith3/ibei
    license: MIT
    summary: Calculator for incomplete Bose-Einstein integral
```
