### ISSUE TITLE
Support pip extra_index_url section in environment files

### ISSUE THREAD

**Issue by analog-cbarber** [conda/conda#12557]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

In my environment files sometimes find it useful to import python packages from pip that are not available in a conda repository, e.g.

```yaml
dependencies:
   - pip
   - pip:
      - non-conda-package  
```

This works fine as long as the package is in the main pypi index, but fails if it lives somewhere else
such as an internal enterprise python repo.

You can work around this by specifying the index URL using the `PIP_EXTRA_INDEX_URL` environment
variable, but it would be nice if you could just put it directly in the environment file, just as you can already
do with channels, e.g.:

```yaml
pip-extra-index-urls:
   - https://evilco.com/pypi/simple
dependencies:
   - pip
   - pip:
      - non-conda-package  
```
