### ISSUE TITLE
Properly include channels and channel prefix into `conda env export --from-history`

### ISSUE THREAD

**Issue by liqimai** [conda/conda#12842]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

# Abstract
In short, I want the package list created by `conda env export --explicit` to be concise, cross-platform, and highly reproducible.  There are two drawbacks in its current output.

## 1. the missing channel problem
Now, `conda env export --from-history` includes packages that I’ve explicitly asked for. It works well when I only install packages from default channels. If I have installed some packages from third-party channels, such as `pytorch`. It would not include the third-party channels. 

e.g. Here is the command to install pytorch.
```
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
```

Here is the output of `conda env export --explicit`
```yml
name: motion
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - torchaudio
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
prefix: /opt/conda/envs/motion
```
The channel `pytorch` is missed, because I did NOT add 'pytorch' channel by `conda config --add channels pytorch`, but just temporally add it by `conda install -c pytorch`.

## 2. the channel ambiguity
Nowadays, users usually install a package from a channel by `conda install -c` command. For the sake of cross-platform reproducibility, we should also include the channel prefix in the output of `conda env export --explicit`. e.g.
```yml
  - pytorch::pytorch-cuda=11.8    # add prefix "pytorch::"
  - pytorch::pytorch              # add prefix "pytorch::"
```
This is because `pytorch` exists both in `conda-forge` and `pytorch` channel. To avoid the ambiguity, we need to explicitly specify the pytorch in `pytorch` channel.

### Why is this needed?

It should include __all channels__ these explicit packages come from, and add precise __channel prefixes__ to the packages that come from non-default channels.  see "What should happen?" for an example.

### What should happen?

Here is an `environment.yml` I created manually. It represents the output of `conda env export --from-history` I expected and requested in this issue. 

It differs from the current output of `conda env export --explicit` in the following ways:
1. all channels are included, as long as any package user asked comes from the channel, even if the channel is not added to config by `conda config --add channels`.
2. add a channel prefix to the package, if the package does not come from the default channel.

```yml
name: myenv
channels:
  - pytorch3d
  - pytorch
  - huggingface
  - nvidia
  - defaults
  - conda-forge
dependencies:
  # packages from the default channel
  - python==3.10
  - dm-tree
  - matplotlib
  - pytest
  - rich
  - ipython
  - ipykernel
  - scipy

  # packages with channel prefix, i.e., installed by `conda install -c <channel> <package>`
  - pytorch::pytorch-cuda=11.8
  - pytorch::pytorch
  - pytorch::torchaudio
  - pytorch::torchvision
  - conda-forge::yapf~=0.32
  - conda-forge::ipywidgets
  - conda-forge::wandb
  - conda-forge::accelerate
  - huggingface::transformers
  - huggingface::datasets
  - pytorch3d::pytorch3d

  # pip packages
  - pip:
      - mpmath==1.2.1
      - pyqt5-sip==12.11.0
prefix: /opt/conda/envs/myenv
```
