### ISSUE TITLE
Allow auth handler plugins to match URL prefix via `channel_settings`

### ISSUE THREAD

**Issue by mattkram** [conda/conda#13778]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Extend the `channel_settings.channel` field to allow specifying a URL prefix with a wildcard suffix syntax, e.g. `https://repo.anaconda.cloud/repo/*`.

### Why is this needed?

With the new auth handler plugin, The `channel_settings` must be set explicitly for each channel:

```yaml
# .condarc
channels: 
  - https://repo.anaconda.cloud/repo/my-organization/my-channel

channel_settings:
  - channel: https://repo.anaconda.cloud/repo/my-organization/my-channel
    auth: anaconda-cloud-auth
```

But this gets cumbersome for multiple channels at the same prefix, since each new channel requires an addition both to `channels:` and `channel_settings`:

```yaml
# .condarc
channels:
  - https://repo.anaconda.cloud/repo/my-organization/my-channel
  - https://repo.anaconda.cloud/repo/my-organization/my-other-channel

channel_settings:
  - channel: https://repo.anaconda.cloud/repo/my-organization/my-channel
    auth: anaconda-cloud-auth
  - channel: https://repo.anaconda.cloud/repo/my-organization/my-other-channel
    auth: anaconda-cloud-auth
```

### What should happen?

Given the following example, both listed channels would use the `anaconda-cloud-auth` plugin:

```yaml
channels:
  - https://repo.anaconda.cloud/repo/my-organization/my-channel
  - https://repo.anaconda.cloud/repo/my-organization/my-other-channel

channel_settings:
  - channel: https://repo.anaconda.cloud/repo/*
    auth: anaconda-cloud-auth
```

If a `channel_settings.channel` ends with `/*`, then any channel whose URL matches the prefix will match the specified `channel_settings.auth` plugin.

### Additional Context

This may or may not be considered a duplicate of #12295, but since it's more specific I decided to open a new issue to tie to an incoming PR. Feel free to integrate issues if that makes more sense!
