### ISSUE TITLE
LinkError conda.core.link:_execute(740) when creating an environment with Jupyter

### ISSUE THREAD

**Issue by amole-arup** [conda/conda#13822]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I tried to create an environment using `conda env create -f file.yml`, containing python 3.10 and jupyter, nbconvert and ipympl using conda-forge channel. It completed "transaction preparation" and "verification" and was carrying out the "transaction execution" when it failed with the following error: `'"C:\Users\user.name\AppData\Local\miniforge3\envs\arup-env2\Scripts\jupyter-nbextension.exe"' is not recognized as an internal or external command, operable program or batch file.`

Any idea why this should be the case and what we can do to fix it?

The full error is as follows:
```shell
(base) C:\Users\user.name>conda env create -f "YAML-files\arup-env.yml"
Retrieving notices: ...working... done
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 24.3.0

Please update conda by running

    $ conda update -n base -c conda-forge conda

Or to minimize the number of packages updated during conda update use

     conda install conda=24.3.0



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: | '"C:\Users\user.name\AppData\Local\miniforge3\envs\arup-env2\Scripts\jupyter-nbextension.exe"' is not recognized as an internal or external command,
operable program or batch file.

done
ERROR conda.core.link:_execute(740): An error occurred while installing package 'conda-forge::widgetsnbextension-3.5.2-py310h5588dad_1'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::widgetsnbextension-3.5.2-py310h5588dad_1
location of failed script: C:\Users\user.name\AppData\Local\miniforge3\envs\arup-env2\Scripts\.widgetsnbextension-post-link.bat
==> script messages <==
'"C:\Users\user.name\AppData\Local\miniforge3\envs\arup-env2\Scripts\jupyter-nbextension.exe"' is not recognized as an internal or external command,
operable program or batch file.

==> script output <==
stdout:
stderr:
return code: 1

()


(base) C:\Users\user.name>conda activate arup-env2

(arup-env2) C:\Users\user.name>conda list
# packages in environment at C:\Users\user.name\AppData\Local\miniforge3\envs\arup-env2:
#
# Name                    Version                   Build  Channel

(arup-env2) C:\Users\user.name>
```

### Conda Info

```shell
(base) C:\Users\user.name>conda info

     active environment : base
    active env location : C:\Users\user.name\AppData\Local\miniforge3
            shell level : 1
       user config file : C:\Users\user.name\.condarc
 populated config files : C:\Users\user.name\AppData\Local\miniforge3\.condarc
                          C:\Users\user.name\.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.2=0
                          __win=0=0
       base environment : C:\Users\user.name\AppData\Local\miniforge3  (writable)
      conda av data dir : C:\Users\user.name\AppData\Local\miniforge3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\user.name\AppData\Local\miniforge3\pkgs
                          C:\Users\user.name\.conda\pkgs
                          C:\Users\user.name\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\user.name\AppData\Local\miniforge3\envs
                          C:\Users\user.name\.conda\envs
                          C:\Users\user.name\micromamba\envs
                          C:\Users\user.name\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Windows/10 Windows/10.0.22631
          administrator : False
             netrc file : None
           offline mode : False


(base) C:\Users\user.name>
```

### Conda Config

```shell
(base) C:\Users\user.name>conda config --show-sources
==> C:\Users\user.name\AppData\Local\miniforge3\.condarc <==
channels:
  - conda-forge

==> C:\Users\user.name\.condarc <==
auto_activate_base: True
envs_dirs:
  - C:\Users\user.name\AppData\Local\miniforge3\envs\
  - C:\Users\user.name\.conda\envs\
  - C:\Users\user.name\micromamba\envs\
  - C:\Users\user.name\Jesmond\
ssl_verify: C:\ProgramData\Arup\Certificates\curl-ca-bundle.crt
channel_priority: strict
channels:
  - conda-forge


(base) C:\Users\user.name>
```

### Conda list

```shell
(arup-env2) C:\Users\user.name>conda list --show-channel-urls
# packages in environment at C:\Users\user.name\AppData\Local\miniforge3\envs\arup-env2:
#
# Name                    Version                   Build  Channel

(arup-env2) C:\Users\user.name>
```

### Additional Context

These are the contents of the environment file...
```yaml
name: arup-env2
channels:
  - conda-forge
dependencies:
  - python=3.10
  # Excel interaction
  - openpyxl
  - xlrd
  - xlwt
  - xlwings
  # Jupyter notebooks
  - jupyter
  - nbconvert
  - ipympl
  # Plotting
  - matplotlib
  - seaborn
  - bokeh
  - plotly
  # Dataframes for vector & tabular data
  - pandas
  - xarray
  - scipy
  - numba
  - qgrid
  - dtale
  # Machine learning
  - scikit-learn
  - keras
  # GIS
  - geopandas
  - shapely
  - rasterio
  - pyproj
  # .NET & DLL interaction
  - pythonnet
  # Code testing, checking and formatting
  - pytest
  - pycodestyle
  - flake8
  - mccabe
  - pyflakes
  - black
  - pydantic
  - mypy
  # Microsoft Authentication
  - msal
  # Graphical user interfaces
  - easygui
  - gooey
  # Automation
  - pywinauto
  - pip
  - pip:
    - pyrevit    
    - sectionproperties
    - sectionproperties[pardiso]
    - sectionproperties[dxf]   
    - sectionproperties[rhino]
```
