### ISSUE TITLE
Reference existing environment variables when specifying envvars in `environment.yml`

### ISSUE THREAD

**Issue by ericmjl** [conda/conda#13952]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

I would like to see the ability to specify environment variables inside `environment.yml` that reference other existing environment variables.

### Why is this needed?

This would allow us to non-destructively set environment variables `LD_LIBRARY_PATH` by appending or prepending to it. Having this feature enabled would allow us to better use conda to install CUDA libraries, for example.

### What should happen?

User should be able to specify, in `environment.yml`, the following types of variables (illustrative examples shown):

```yaml
name: my-env
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.11
  - ...
  - cuda-libraries
variables: # SEE HERE!
  LD_LIBRARY_PATH: $CONDA_PREFIX/lib:$LD_LIBRARYPATH
  DOWNLOAD_PATH: $HOME/Downloads
```
