### ISSUE TITLE
Using Artifact Attestations

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#13965]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Recently at the Scientific Python Summit @matthewfeickert pointed out that GitHub has provided support for Artifact Attestations using [Sigstore]( https://www.sigstore.dev ) ( https://github.com/scientific-python/summit-2024/issues/9 ). This is also covered in [this GitHub blogpost from last month]( https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/ )

The process uses artifacts built in a GitHub Action workflow to create the Attestation. Given we have recently gone through the work of setting up Conda ( https://github.com/conda/conda/issues/13399 ) and Conda-Build ( https://github.com/conda/conda-build/issues/5340 ) to use GitHub Actions to create source artifacts, think it would be a good idea to go a step further and setup Attestations for them as well

Given both Conda & Conda-build (and possible other Conda projects; especially those in the incubator), could benefit we may want to set this up in a shared space

### Why is this needed?

This would provide clarity to consumers of our source artifacts how they were generated with checksums, links to the GHA workflow used, author, etc.

Generally this should help provide consumers more trust around our artifact process

### What should happen?

AIUI there are 2 main pieces, the workflow that produces our source artifacts would need these permission changes

```yaml
permissions:
  id-token: write
  attestations: write
  contents: read
```

Then after the source artifact is created, we would add this step to generate the attestations

```yaml
    - name: Attest Build Provenance
        uses: actions/attest-build-provenance@897ed5eab6ed058a474202017ada7f40bfa52940 # v1.0.0
        with:
        subject-path: "<artifact path>"
```

Have copied and tweaked these from the GitHub blogpost above
