### ISSUE TITLE
Proxy configuration per URL

### ISSUE THREAD

**Issue by jasongrout** [conda/conda#1527]
In a complex network with multiple proxies, requests need to be routed to different proxies that depend on the URL.  I propose that we extend the proxy_servers key in the conda config to support arbitrary prefixes, rather than just 'http' and 'https' keys, and that the longest matching key should be used.

For example, the proxy_servers config could be:

```yaml
proxy_servers:
    http: http://some.proxy.com:8080
    https: https://some.proxy.com:8081
    'http://some.internal.url': http://internal.proxy.com
    'http://some.external.url': http://external.proxy.com
```
Any request is matched to the longest string, and that given proxy is used.

A weakness of this proposal is that often you want to match the end of a domain name in proxy configurations, i.e., any domain that ends in 'mycompany.com' should use a specific proxy.  However, for the specific purposes of conda, perhaps it's all right to hardcode the specific url conda would use, like 'http://mypackages.mycompany.com'.

This addresses, in a way, the problems in #190.
