### ISSUE TITLE
h5py >=2.4.0 not detected by pip/setuptools

### ISSUE THREAD

**Issue by ikalev** [conda/conda#1529]
I'm trying to build a conda package which depends on ``h5py``. Here's a fragment from my ``meta.yaml`` recipe:

```
build:
  binary_relocation: true
  number: 0
  script: python setup.py install
package:
  name: xyz
  version: 0.2.1
requirements:
  build:
  - h5py 
  - python
  run:
  - h5py 
  - python
source:
  path: C:\source
test:
  requires: []
```

When I try to build this package, setuptools does not detect that ``h5py`` is already installed in the build environment and the build fails:

```
c:\> conda build c:\recipe
...
Processing dependencies for xyz==0.2.1
Searching for h5py

RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.o
rg/simple/h5py/r
```

It works fine if I change the requirement to ``h5py <=2.3``. But since version 2.4 h5py can't be detected by pip or setuptools:

```
C:\>conda create -n bug pip
C:\>activate bug

[bug] C:\>conda install h5py=2.3
[bug] C:\>pip install h5py
Requirement already satisfied (use --upgrade to upgrade): h5py in c:\anaconda\envs\bug\lib\site-packages

[bug] C:\>conda install h5py=2.4
[bug] C:\>pip install h5py
Collecting h5py
  Using cached h5py-2.5.0.tar.gz
```

This might be the case because ``conda install h5py=2.3`` installs ``h5py-2.3.1-py2.7.egg-info`` in ``site-packages``, but this directory is missing if you install ``h5py >=2.4``.
