### ISSUE TITLE
valid YAML recipe fails on conda build due to 'invalid YAML'

### ISSUE THREAD

**Issue by naught101** [conda/conda#1540]
`conda 3.11.0`, using 

```
$ conda list
# packages in environment at /home/naught101/miniconda3/envs/ggplotdev:
#
anaconda-build            0.10.7                   py34_0  
anaconda-client           1.0.1                    py34_0  
binstar                   0.12                          2  
binstar-build             0.8.3                     <pip>
brewer2mpl                1.4                      py34_0  
...
python                    3.4.3                         1  
...
yaml                      0.1.6                         0  
zlib                      1.2.8                         0  
```

This recipe fails:

``` yaml
$ cat recipe/meta.yaml
about: {home: 'https://github.com/jiffyclub/brewer2mpl/wiki', license: MIT License,
  summary: Connect colorbrewer2.org color maps to Python and matplotlib}
build:
  entry_points: []
  features: []
  script_env: []
  string: ''
  track_features: []
package: {name: brewer2mpl, version: '1.4'}
requirements:
  build: [python]
  conflicts: []
  run: [python]
source:
  fn: brewer2mpl-1.4.tar.gz
  git_rev: ''
  md5: 49b7f7de78a5a47021aee91bee543026
  patches: []
  path: ''
  svn_rev: ''
  url: https://pypi.python.org/packages/source/b/brewer2mpl/brewer2mpl-1.4.tar.gz
test:
  commands: []
  files: []
  imports: [brewer2mpl, brewer2mpl.wesanderson]
  requires: []
```

This is a meta.yaml _produced by `conda build`_. If I want to re-use it to build a package elsewhere, I can try, but it will fail:

``` bash
$ conda build recipe
Error: Invalid selector in meta.yaml line 11:
  build: [python]
```

The YAML is perfectly valid, as far as I can see (it passes on http://www.yamllint.com/). `conda buil` fails on all such lines. I can only make it work by changing such lines to, e.g.:

``` yaml
  imports: 
    - brewer2mpl
    - brewer2mpl.wesanderson
```

if I change the python line to:

``` yaml
  build: python
```

it complains about there being no package 'p' available (presumably it's treating the string as a list..)
