### ISSUE TITLE
Package versions with features are not correctly resolved

### ISSUE THREAD

**Issue by ukoethe** [conda/conda#1589]
Initially, I thought this was conda's intended behavior, but now I suspect it is a bug. Suppose I built packages 

```
track_vc11-1.0-0.tar.bz2
foo-1.0-0.tar.bz2
foo-1.0-vc11.tar.bz2
foo-2.0-0.tar.bz2
use_foo-1.0-vc11.tar.bz2
```

from the following `meta.yaml` files:

``` yaml
package:
  name:  track_vc11
  version: "1.0"
build:
  features:
    - vc11
  track_features:
    - vc11
```

``` yaml
package:
  name:  foo
  version: "1.0"
```

``` yaml
package:
  name:  foo
  version: "1.0"
build:
  string: vc11
  features:
    - vc11
requirements:
  build:
    - track_vc11
  run:
    - track_vc11
```

``` yaml
package:
  name:  foo
  version: "2.0"
```

``` yaml
package:
  name:  use_foo
  version: "1.0"
build:
  string: vc11
  features:
    - vc11
requirements:
  build:
    - track_vc11
    - foo
  run:
    - track_vc11
    - foo
```

Now I create an environment where `vc11` is being tracked:

```
conda create --use-local -n vc11 track_vc11
activate vc11
```

Within this environment, I install `use_foo` and get:

```
The following NEW packages will be INSTALLED:

    foo:     2.0-0
    use_foo: 1.0-vc11 [vc11]
```

However, I expected the output to be

```
    foo:     1.0-vc11 [vc11]
    use_foo: 1.0-vc11 [vc11]
```

because only `foo-1.0-vc11.tar.bz2` has the required feature `vc11`. I digged a bit into the code and found the suspicious statement ([resolve.py#477](https://github.com/conda/conda/blob/master/conda/resolve.py#L477))

``` python
            dists = self.get_dists(specs, max_only=True)
```

When I changed this into

``` python
            dists = self.get_dists(specs, max_only=False)
```

I got the desired output.
