### ISSUE TITLE
Miniconda fails to build test on Travis CI with Py3.3 and 3.4 but not 2.7 ("can't set attribute")

### ISSUE THREAD

**Issue by robclewley** [conda/conda#1728]
Here is the full traceback from Travis while trying to install and test my package (PyDSTool). The same setup works for Py2.7 but maybe something is wrong in the configs, and this setup used to work a few months ago. I can't tell if this is conda's fault: if not, please point me in the right direction and I'll ask elsewhere.

```
Setting environment variables from .travis.yml
$ export NUMPY_SPEC=numpy
$ export SCIPY_SPEC=scipy
$ export COVERAGE="no"
0.01s$ source ~/virtualenv/python3.3/bin/activate
$ python --version
Python 3.3.5
$ pip --version
pip 6.0.7 from /home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages (python 3.3)
before_install.1
8.40s$ sudo apt-get update -qq
before_install.2
4.08s$ sudo apt-get install -qq gfortran swig
Selecting previously unselected package gfortran-4.6.
(Reading database ... 77803 files and directories currently installed.)
Unpacking gfortran-4.6 (from .../gfortran-4.6_4.6.3-1ubuntu5_amd64.deb) ...
Selecting previously unselected package gfortran.
Unpacking gfortran (from .../gfortran_4%3a4.6.3-1ubuntu5_amd64.deb) ...
Selecting previously unselected package swig2.0.
Unpacking swig2.0 (from .../swig2.0_2.0.4+really2.0.4-4ubuntu2_amd64.deb) ...
Selecting previously unselected package swig.
Unpacking swig (from .../swig_2.0.4+really2.0.4-4ubuntu2_amd64.deb) ...
Processing triggers for man-db ...
Processing triggers for ccache ...
Updating symlinks in /usr/lib/ccache ...
Setting up gfortran-4.6 (4.6.3-1ubuntu5) ...
Setting up gfortran (4:4.6.3-1ubuntu5) ...
update-alternatives: using /usr/bin/gfortran to provide /usr/bin/f95 (f95) in auto mode.
Setting up swig2.0 (2.0.4+really2.0.4-4ubuntu2) ...
Setting up swig (2.0.4+really2.0.4-4ubuntu2) ...
before_install.3
0.26s$ wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
--2015-10-22 08:08:15--  http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 23.21.82.148, 23.21.145.66, 23.23.112.241, ...
Connecting to repo.continuum.io (repo.continuum.io)|23.21.82.148|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24166764 (23M) [application/octet-stream]
Saving to: `miniconda.sh'
100%[======================================>] 24,166,764   101M/s   in 0.2s    
2015-10-22 08:08:15 (101 MB/s) - `miniconda.sh' saved [24166764/24166764]
before_install.4
0.01s$ chmod +x miniconda.sh
before_install.5
6.28s$ ./miniconda.sh -b
PREFIX=/home/travis/miniconda
installing: python-2.7.10-0 ...
installing: conda-env-2.4.2-py27_0 ...
installing: openssl-1.0.1k-1 ...
installing: pycosat-0.6.1-py27_0 ...
installing: pyyaml-3.11-py27_1 ...
installing: readline-6.2-2 ...
installing: requests-2.7.0-py27_0 ...
installing: sqlite-3.8.4.1-1 ...
installing: tk-8.5.18-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-0 ...
installing: conda-3.16.0-py27_0 ...
installing: pycrypto-2.6.1-py27_0 ...
Python 2.7.10 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
before_install.6
0.01s$ export PATH=/home/travis/miniconda/bin:$PATH
before_install.7
8.93s$ conda update --yes conda
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /home/travis/miniconda:
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2d             |                0         3.2 MB
    python-2.7.10              |                2        12.0 MB
    requests-2.8.1             |           py27_0         603 KB
    setuptools-18.4            |           py27_0         342 KB
    wheel-0.26.0               |           py27_1          76 KB
    conda-3.18.3               |           py27_0         175 KB
    pip-7.1.2                  |           py27_0         1.4 MB
    ------------------------------------------------------------
                                           Total:        17.7 MB
The following NEW packages will be INSTALLED:
    pip:        7.1.2-py27_0 
    setuptools: 18.4-py27_0  
    wheel:      0.26.0-py27_1
The following packages will be UPDATED:
    conda:      3.16.0-py27_0 --> 3.18.3-py27_0
    openssl:    1.0.1k-1      --> 1.0.2d-0     
    python:     2.7.10-0      --> 2.7.10-2     
    requests:   2.7.0-py27_0  --> 2.8.1-py27_0 
Fetching packages ...
openssl-1.0.2d 100% |################################| Time: 0:00:00  37.10 MB/s
python-2.7.10- 100% |################################| Time: 0:00:00  36.09 MB/s
requests-2.8.1 100% |################################| Time: 0:00:00  25.51 MB/s
setuptools-18. 100% |################################| Time: 0:00:00  16.84 MB/s
wheel-0.26.0-p 100% |################################| Time: 0:00:00  10.90 MB/s
conda-3.18.3-p 100% |################################| Time: 0:00:00  15.47 MB/s
pip-7.1.2-py27 100% |################################| Time: 0:00:00  28.18 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
install.1
30.87s$ conda install --yes python=$TRAVIS_PYTHON_VERSION atlas $NUMPY_SPEC $SCIPY_SPEC pytest six mock
Fetching package metadata: ....
Solving package specifications: ......................
Package plan for installation in environment /home/travis/miniconda:
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    atlas-3.8.4                |                0         3.0 MB
    system-5.8                 |                2         170 KB
    xz-5.0.5                   |                0         504 KB
    python-3.3.5               |                4        19.7 MB
    conda-env-2.4.2            |           py33_0          24 KB
    funcsigs-0.4               |           py33_0          19 KB
    numpy-1.9.2                |           py33_0         7.5 MB
    py-1.4.30                  |           py33_0         126 KB
    pycosat-0.6.1              |           py33_0         152 KB
    pyyaml-3.11                |           py33_1         303 KB
    requests-2.8.1             |           py33_0         603 KB
    setuptools-18.4            |           py33_0         355 KB
    six-1.10.0                 |           py33_0          17 KB
    wheel-0.26.0               |           py33_1          77 KB
    conda-3.18.3               |           py33_0         179 KB
    pip-7.1.2                  |           py33_0         1.5 MB
    pytest-2.7.2               |           py33_0         196 KB
    scipy-0.16.0               |       np19py33_0        38.1 MB
    pbr-1.3.0                  |           py33_0          84 KB
    mock-1.3.0                 |           py33_0          99 KB
    ------------------------------------------------------------
                                           Total:        72.6 MB
The following NEW packages will be INSTALLED:
    atlas:      3.8.4-0          
    funcsigs:   0.4-py33_0       
    mock:       1.3.0-py33_0     
    numpy:      1.9.2-py33_0     
    pbr:        1.3.0-py33_0     
    py:         1.4.30-py33_0    
    pytest:     2.7.2-py33_0     
    scipy:      0.16.0-np19py33_0
    six:        1.10.0-py33_0    
    system:     5.8-2            
    xz:         5.0.5-0          
The following packages will be UPDATED:
    conda:      3.18.3-py27_0 --> 3.18.3-py33_0    
    conda-env:  2.4.2-py27_0  --> 2.4.2-py33_0     
    pip:        7.1.2-py27_0  --> 7.1.2-py33_0     
    pycosat:    0.6.1-py27_0  --> 0.6.1-py33_0     
    python:     2.7.10-2      --> 3.3.5-4          
    pyyaml:     3.11-py27_1   --> 3.11-py33_1      
    requests:   2.8.1-py27_0  --> 2.8.1-py33_0     
    setuptools: 18.4-py27_0   --> 18.4-py33_0      
    wheel:      0.26.0-py27_1 --> 0.26.0-py33_1    
The following packages will be DOWNGRADED:
    openssl:    1.0.2d-0      --> 1.0.1k-1         
Fetching packages ...
atlas-3.8.4-0. 100% |################################| Time: 0:00:00  32.07 MB/s
system-5.8-2.t 100% |################################| Time: 0:00:00  13.81 MB/s
xz-5.0.5-0.tar 100% |################################| Time: 0:00:00  21.63 MB/s
python-3.3.5-4 100% |################################| Time: 0:00:00  36.12 MB/s
conda-env-2.4. 100% |################################| Time: 0:00:00   5.77 MB/s
funcsigs-0.4-p 100% |################################| Time: 0:00:00   9.90 MB/s
numpy-1.9.2-py 100% |################################| Time: 0:00:00  31.13 MB/s
py-1.4.30-py33 100% |################################| Time: 0:00:00  11.80 MB/s
pycosat-0.6.1- 100% |################################| Time: 0:00:00  13.79 MB/s
pyyaml-3.11-py 100% |################################| Time: 0:00:00  15.42 MB/s
requests-2.8.1 100% |################################| Time: 0:00:00  17.14 MB/s
setuptools-18. 100% |################################| Time: 0:00:00  22.66 MB/s
six-1.10.0-py3 100% |################################| Time: 0:00:00   6.89 MB/s
wheel-0.26.0-p 100% |################################| Time: 0:00:00  14.41 MB/s
conda-3.18.3-p 100% |################################| Time: 0:00:00  11.28 MB/s
pip-7.1.2-py33 100% |################################| Time: 0:00:00  30.71 MB/s
pytest-2.7.2-p 100% |################################| Time: 0:00:00  16.04 MB/s
scipy-0.16.0-n 100% |################################| Time: 0:00:00  40.40 MB/s
pbr-1.3.0-py33 100% |################################| Time: 0:00:00   8.33 MB/s
mock-1.3.0-py3 100% |################################| Time: 0:00:00  10.09 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
install.2
0.01s$ if [ "${COVERAGE}" == "yes" ]; then conda install --yes -c dan_blanchard coverage python-coveralls; fi
0.40s$ if [ "${COVERAGE}" == "yes" ]; then sed -i'' -e 's/--boxed//g' pytest.ini && coverage run --source=PyDSTool setup.py test -q; else python setup.py test; fi
running test
Traceback (most recent call last):
  File "setup.py", line 118, in <module>
    "Operating System :: POSIX :: Linux",
  File "/home/travis/miniconda/lib/python3.3/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/travis/miniconda/lib/python3.3/distutils/dist.py", line 930, in run_commands
    self.run_command(cmd)
  File "/home/travis/miniconda/lib/python3.3/distutils/dist.py", line 948, in run_command
    cmd_obj.ensure_finalized()
  File "/home/travis/miniconda/lib/python3.3/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 66, in finalize_options
    self.test_args = [a for a in self.test_args if a is not None]
AttributeError: can't set attribute
```

**Comment by robclewley** [comment]
P.S. Here is my travis config:

```
language: python
matrix:
    include:
        - python: 3.4
          env:
            - NUMPY_SPEC=numpy
            - SCIPY_SPEC=scipy
            - COVERAGE="no"
        - python: 3.3
          env:
            - NUMPY_SPEC=numpy
            - SCIPY_SPEC=scipy
            - COVERAGE="no"
        - python: 2.7
          env:
            - NUMPY_SPEC=numpy
            - SCIPY_SPEC=scipy
            - COVERAGE="yes"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq gfortran swig

    # Use miniconda. Taken from https://gist.github.com/dan-blanchard/7045057
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas $NUMPY_SPEC $SCIPY_SPEC pytest six mock
    - if [ "${COVERAGE}" == "yes" ]; then conda install --yes -c dan_blanchard coverage python-coveralls; fi

script:
    - if [ "${COVERAGE}" == "yes" ]; then sed -i'' -e 's/--boxed//g' pytest.ini && coverage run --source=PyDSTool setup.py test -q; else python setup.py test; fi

after_success:
    - if [ "${COVERAGE}" == "yes" ]; then coveralls --config_file .coveragerc; fi

cache: apt
```
