### ISSUE TITLE
Conda recipe for building conda

### ISSUE THREAD

**Issue by rekcahpassyla** [conda/conda#1782]
Maybe a chicken and egg problem- I cannot find documented instructions for building conda itself anywhere (perhaps I didn't look hard enough?) Tried  https://github.com/conda/conda-recipes/tree/master/conda  which doesn't work.

**Comment by rekcahpassyla** [comment]
By adapting @pelson 's https://github.com/pelson/raspberrypi-conda-recipes/tree/master/recipes/conda , and https://github.com/conda/conda-recipes/tree/master/conda  the following work for me on windows

bld.bat:
```
set CONDA_DEFAULT_ENV=
python setup.py install
if errorlevel 1 exit 1

del %SCRIPTS%\conda-init
if errorlevel 1 exit 1
```

meta.yaml:
```
package:
  name: conda
  version: 3.18.3.post14+g74f2909

source:
  git_url: https://github.com/conda/conda.git
  git_tag: 74f2909046495d3f3982301f1f833aa8deddbd5a

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python
    - pycosat
    - pyyaml
    - requests

test:
  commands:
    - conda --version
    - conda info
  imports:
    - conda

about:
  home: http://conda.pydata.org/
  license: BSD
```
