### ISSUE TITLE
`nomkl` correctly used in `build` section but not in `run` section of recipe

### ISSUE THREAD

**Issue by desilinguist** [conda/conda#2064]
I am trying to disable the use of `mkl` for my conda package. Here's the relevant section for `meta.yaml`:

```yaml
requirements:
  build:
    - python
    - ipython 4.0.1
    - jupyter 1.0.0
    - joblib 0.8.4
    - matplotlib 1.5.1
    - nose 1.3.7
    - notebook 4.1.0
    - nomkl # [unix]
    - numpy >=1.10.1,<=1.10.2
    - pandas 0.17.1
    - scikit-learn 0.16.1
    - scipy >=0.16.0,<=0.16.1
    - seaborn 0.6.0
    - skll 1.1.1
    - statsmodels 0.6.1
    - zeromq 4.1.3
    - setuptools
    - six

  run:
    - python
    - ipython 4.0.1
    - jupyter 1.0.0
    - joblib 0.8.4
    - matplotlib 1.5.1
    - nose 1.3.7
    - notebook 4.1.0
    - nomkl # [unix]
    - numpy >=1.10.1,<=1.10.2
    - pandas 0.17.1
    - scikit-learn 0.16.1
    - scipy >=0.16.0,<=0.16.1
    - seaborn 0.6.0
    - skll 1.1.1
    - statsmodels 0.6.1
    - zeromq 4.1.3
    - six
```

However, when I run `conda build` on a linux machine, the build phase correctly installs the `nomkl` version of the `scipy` package but the test phase does not and still goes with the default `mkl`-enabled version.
