### ISSUE TITLE
conda-build fails silently on Mac OS-X Darwin 64bit after upgrade to conda 4.x

### ISSUE THREAD

**Issue by csadorf** [conda/conda#2352]
After updating conda to 4.x one of my recipes fails silently on Mac OS-X Darwin 64bit.

The recipe:
```
package:
  name: my_package
  version: "0.1.9"

build:
  number: 0
  script: python setup.py install
  skip: True #[py26]

source:
  git_rev: v0.1.9
  git_url: [...]
requirements:
  build:
    - python
    - enum34 #[py27 or py33]
    - [..]

  run:
    - python
    - enum34 #[py27 or py33]
    - [..]

test:
  imports:
    - package
```
This is the (minimal) build command:
```
for python_version in 2.7 3.4 3.5
do
    conda-build --python ${python_version} MY_PACKAGE
done
```
And the relevant output:
```
BUILD START: my_package-0.1.9-py34_1
Fetching package metadata: ........
Solving package specifications: .Using Anaconda Cloud api site https://api.anaconda.org
...
TEST START: my_package-0.1.9-py34_1
Fetching package metadata: ........
Solving package specifications: .
Error:  Package missing in current osx-64 channels: 
  - my_package 0.1.9 py34_1
```
The package is not built, there is no indication of error. The recipe works flawlessly with the latest 3.x release.
