### ISSUE TITLE
conda install <package> incorrectly says package is installed

### ISSUE THREAD

**Issue by Zaharid** [conda/conda#3084]
I have a package that I maintain in a custom channel (own server).

When I download conda anew I can

```
<install conda>
conda install libnnpdf
```

perfectly fine. But if I try to remove it and install it again, it says it is installed even thought it is not. Same thing happens with a dependency of that package. I have purged all reference to that package from the anaconda directory that I can find, and so I don't understand  how it decides it's installed:

```
conda clean --all
rm pkgs/urls.txt
rm conda-meta/history
...
```

```
zah@zah-XPS13-9333 ~/anaconda3 $ grep -r libnnpdf .
zah@zah-XPS13-9333 ~/anaconda3 $ conda update libnnpdf
Error: Package 'libnnpdf' is not installed in /home/zah/anaconda3
zah@zah-XPS13-9333 ~/anaconda3 $ conda install libnnpdf
Fetching package metadata .............
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /home/zah/anaconda3:
#

zah@zah-XPS13-9333 ~/anaconda3 $ strace conda install libnnpdf 2>&1 | grep libnnpdf
execve("/home/zah/anaconda3/bin/conda", ["conda", "install", "libnnpdf"], [/* 66 vars */]) = 0

```

Here is the meta.yaml that gets generated:

```
# This file created by conda-build 1.20.3
# meta.yaml template originally from:
# /builds/NNPDF/libnnpdf/conda-recipe, last modified Tue Jun 21 10:12:58 2016
# ------------------------------------------------

package:
    name: libnnpdf
    version: 1.1.0b4.0
source:
    git_url: ../
build:
    detect_binary_files_with_prefix: 'True'
    number: '0'
    script_env:
        - NNPDF_USE_DOUBLE
requirements:
    build:
        - python
        - lhapdf
        - swig
        - sqlite
        - gcc
        - libgcc
        - gsl
        - numpy
    run:
        - lhapdf
        - python
        - sqlite
        - libgcc
        - gsl
        - numpy
test:
    commands:
        - nnpdf-config
about:
    home: https://nnpdf.hepforge.org/
    license: SECRET
```
