### ISSUE TITLE
proxy authentication not working

### ISSUE THREAD

**Issue by nielsenmarkus11** [conda/conda#3124]
I've been having an issue with conda authenticating with our companies proxy server.  If I set the HTTP_PROXY and HTTPS_PROXY environment variables with the username and password it works fine, but saving my password in plain sight isn't a viable option.  The conda configuration states:

"Note: If you do not include the username and password, of if authentication fails, conda will prompt for a username and password."

So I tried setting the proxies without the username and password in my .condarc, but get the following problem:

.condarc
```
# Proxy settings: http://[username]:[password]@[server]:[port]
proxy_servers:
    http: http://proxy.company.com:8080
    https: https://proxy.company.com:8080
ssl_verify: true
```
![image](https://cloud.githubusercontent.com/assets/9438047/17027116/dd9579d0-4f1f-11e6-85a0-e0a688f71182.png)

First, my password is still in plain sight, and second, there seems to be a bug since it prints `https proxy username:` again after I've typed the username but before the `Password:` prompt. Once I hit enter after typing my password, it prompts `https proxy username:` again and as soon as I touch any key it prints the `Password:` prompt.

A fix or any help would be much appreciated.

Thanks.
