### ISSUE TITLE
conda skeleton adds empty test line

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#371]
For example, from `conda skeleton pypi`:

``` yaml
test:
  # Python imports
  imports:
    - py
    - py._log
    - py._code
    - py._process
    - py._path
    -
    - py
    - py._io
```

Another issue is that `py` is in there twice.
