### ISSUE TITLE
support per-channel proxy configuration

### ISSUE THREAD

**Issue by taoluo** [conda/conda#3719]
this PR (#1171) support no_proxy as env variable, while I am wondering can I add no_proxy in the configure file just like what we do with http_proxy.

**Comment by kalefranz** [comment]
`http_proxy` doesn't go in the config file, according to #1171, but instead is an environment variable.  All of #1171 should still be in effect.

**Comment by mickeydonkey** [comment]
Yeh, @kalefranz are right. To be clear, I mean we can add proxy_servers option to `.condarc`  which is equivalent to set http_proxy in the shell. I am seeking for a no_proxy-equivalent option in config file.

**Comment by mickeydonkey** [comment]
I think something like following will accomplish my request?
```
proxy_servers:
    http: http://127.0.0.1:1080
    https: http://127.0.0.1:1080
    'repo.continuum.io': no_proxy
```
