### ISSUE TITLE
File to patch not found

### ISSUE THREAD

**Issue by peter1000** [conda/conda#447]
I encountered sometimes this issue: maybe someone knows:

When I specify in a meta.yaml a path: e.g.

```
source:
  fn: openssl-1.0.1e.tar.gz
  url: https://www.openssl.org/source/openssl-1.0.1e.tar.gz

  patches:
    - openssl-1.0.1e-fix_pod_syntax-1.patch

```

I get stuck in 

```
Found source in cache: openssl-1.0.1e.tar.gz
Applying patch: '/home/workerm/0_CONDA_RELATED_0/conda-recipes/toolchain_stage1/openssl_stage1/openssl-1.0.1e-fix_pod_syntax-1.patch'
can't find file to patch at input line 11
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|Submitted By: Martin Ward <macros_the_black at ntlworld dot com>
|Date: 2013-06-18
|Initial Package Version: 1.0.1e
|Upstream Status: Unknown
|Origin: self, based on fedora
|Description: Fixes install with perl-5.18.
|
|diff -Naur openssl-1.0.1e.orig/doc/apps/cms.pod openssl-1.0.1e/doc/apps/cms.pod
|--- openssl-1.0.1e.orig/doc/apps/cms.pod   2013-06-06 14:35:15.867871879 +0100
|+++ openssl-1.0.1e/doc/apps/cms.pod    2013-06-06 14:35:25.791747119 +0100
--------------------------
File to patch: 

```

I can successfully do it within the build.sh

```
patch -Np1 -i $RECIPE_DIR/openssl-1.0.1e-fix_pod_syntax-1.patch
```

but would prefer to follow the correct conda way?
