### ISSUE TITLE
`conda build .` deletes scripts in "bin" folder

### ISSUE THREAD

**Issue by dragly** [conda/conda#4491]
When building a simple conda package with 
```conda build .```
it ends up deleting any scripts mentioned in the scripts-argument of the setup function in setup.py.

Here is an example setup.py file which causes the issue:

```python
from setuptools import setup
import os

from setuptools import setup, find_packages

long_description = open("README.md").read()

entry_points = None

install_requires = []

setup(
    name="Package name",
    packages=find_packages(),
    entry_points=entry_points,
    include_package_data=True,
    scripts=["bin/mypackage"]
)
```

The corresponding meta.yaml file looks as follows:
```yaml
package:
  name: mypackage
  version: 0.1
  
source:
  path: .
 
build:
    script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python
    - setuptools
    - pip
```

After running 
```conda build .```
the bin/mypackage file has been deleted.

This does not happen if the build command is issued a directory above the source directory, i.e. 
```conda build mypackage```
