### ISSUE TITLE
Building package from pypi skeleton causes "Package missing in current osx-64 channels" error

### ISSUE THREAD

**Issue by zfrenchee** [conda/conda#4887]
Hi, 

I can't find documentation about how to fix this, and it didn't happen for the previous pypi package I put on Conda, which confuses me. 

```
~ » conda skeleton pypi GarNet
Using url https://pypi.python.org/packages/8c/51/15118d317e5403526934ee0c6fa672bc7a467f7b1d595dda1bb955113fcf/GarNet-0.2.14.tar.gz (28 KB) for GarNet.
Downloading GarNet
Using cached download
Unpacking GarNet...
done
working in /var/folders/0w/fzyy4qz93l56_bh1jyn3vgp00000gn/T/tmp9xvlalcfconda_skeleton_GarNet-0.2.14.tar.gz

The following NEW packages will be INSTALLED:

    openssl:    1.0.2k-1
    pip:        9.0.1-py36_1
    python:     3.6.0-0
    pyyaml:     3.12-py36_0
    readline:   6.2-2
    setuptools: 27.2.0-py36_0
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    wheel:      0.29.0-py36_0
    xz:         5.2.2-1
    yaml:       0.1.6-0
    zlib:       1.2.8-3

Applying patch: '/var/folders/0w/fzyy4qz93l56_bh1jyn3vgp00000gn/T/tmp9xvlalcfconda_skeleton_GarNet-0.2.14.tar.gz/pypi-distutils.patch'
patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 1 line).
Using "GNU General Public License" for the license
Writing recipe for garnet
INFO conda_build.config:__exit__(422): --dirty flag not specified.  Removing build folder after successful build/test.

~ » conda build GarNet
BUILD START: garnet-0.2.14-py36_0
updating index in: /Users/alex/miniconda3/conda-bld/osx-64
updating index in: /Users/alex/miniconda3/conda-bld/noarch
Can't build /Users/alex/GarNet due to unsatisfiable dependencies:
Package missing in current osx-64 channels:
  - intervaltree
```

[`intervaltree`](https://github.com/chaimleib/intervaltree) is just a package on [pypi](https://pypi.python.org/pypi/intervaltree). I think this error is being triggered by something deeper, but I can't find any help online. What's going on? 

Just some extra information from the meta.yml file:

```
requirements:
  build:
    - python
    - numpy
    - pandas
    - statsmodels
    - matplotlib
    - intervaltree
    - jinja2

  run:
    - python
    - numpy
    - pandas
    - statsmodels
    - matplotlib
    - intervaltree
    - jinja2
``` 

Thanks!
