### ISSUE TITLE
Bad interpreation of null in proxy_servers section in .condarc since ver. 4.2.13

### ISSUE THREAD

**Issue by agilevic** [conda/conda#5102]
Upon upgrade to conda to version 4.2.13 the following settings in .condarc, which were meant to unset any http_proxy or https_proxy variables no longer work; result in HTTP error.

```
proxy_servers:
    # Unset proxies so we can define internal channels shouldn't go outside anyway
    http:
    https:
```
Error received upon conda install:

```
An HTTP error occurred when trying to retrieve this URL.
ConnectionError(MaxRetryError("HTTPConnectionPool(host=u'None', port=80): Max retries exceeded with url: http://sfp-inf.jpmchase.net:9000/conda/mrad/channel/dev/linux-64/repodata.json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f197d701610>: Failed to establish a new connection: [Errno -2] Name or service not known',)))",),)
```

The reason is wrongly reinterpreting null values as 'None' string and subsequently trying to connect to hostname 'None'.

For those of you need a workaround now, change your .condarc as follows:

```
proxy_servers:
    # Unset proxies so we can define internal channels shouldn't go outside anyway
    http: ""
    https: ""
```
