### ISSUE TITLE
Installation of noarch package in env does not create entry point

### ISSUE THREAD

**Issue by Lobotomik** [conda/conda#5129]
I can create a noarch package with this yaml file:

```
package:
  name: sview
  version: 0.10.1

source:
  path: \Users\lobotomik\gitspace\sview_git # ..

build:
  number: 1
  string: py_27
  noarch: python
  entry_points:
    - sview = sview.main:main
  include_recipe: False
  
requirements:
  build:
    - python <2.8

  run:
    - python   <2.8
    - apptools >=4.3,<5
    - kiwisolver
    - pyface   >=4.5,<5
    - traits   >=4.5,<5
    - traitsui >=4.5,<5
    - enable   >=4.5,<5
    - chaco    >=4.5,<5
    - numpy    >=1.9

```
The package that is produced can be installed in the global anaconda workspace, and it works OK. A launcher named 'sview' is produced in anaconda\Scripts, and its execution invokes the program.

HOWEVER

If I activate an environment and then install the package _inside_, a launcher script is not created in the environment's Scripts directory. 

Still, I can find the contents of the package in envs/myenv/Lib/site-packages/sview, in particular the .../sview/main.py script referenced in the entry point section of the yaml file. If that script is invoked, the application runs OK.

** EDIT ** The package contents end up not in ..envs/myenv./Lib/site-packages, as said above, but for some reason in envs/myenv/site-packages, unlike the win-64 packages I obtain.

I produce other packages that are not noarch, and those do produce an entry point also when installed in an environment.  It seems that the entry point generation is being skipped for noarch installation in environments only. Or, very likely, I am missing something.
