### ISSUE TITLE
Add --json flag on conda-env that works!

### ISSUE THREAD

**Issue by goanpeca** [conda/conda#5341]
The json flag seems to be there, but it is not working.

With a file that looks like

```yaml
# environment.yaml
name: test_env_1
channels:
- defaults
dependencies:
- python
- pytest-cov
```

```
(root) $ conda-env create --json
Using Anaconda API: http s://api.anaconda.org
(root) $
```

So two problems here:
1.) No json output on the create process
2.) `Using Anaconda API: https://api.anaconda.org`
