### ISSUE TITLE
setuptools and noarch packages?

### ISSUE THREAD

**Issue by sbourdeauducq** [conda/conda#5486]
With the new noarch system, how am I supposed to create a noarch package that uses setuptools?

If setuptools cannot be used with noarch, how to handle things like a long list of entry points, MANIFEST.in files, and versioneer?

**Comment by mbargull** [comment]
That's an issue for https://github.com/conda/conda-build/issues ;).
Nonetheless, I use this in `meta.yaml`:
```yaml
build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
```
This uses the `script` entry to specify the call to `setup.py` for any platform (which was previously in the now obsolete `bld.bat`/`build.sh`).
