### ISSUE TITLE
Conda hangs when solving package specifications

### ISSUE THREAD

**Issue by daler** [conda/conda#5536]
Hi, here is another data point related to #5219, #4077, #4467 where the solver hangs on particular combos of dependencies. Pinging @mcg1969 since you're mentioned in those other issues.

After trying different combinations trying to pin down the culprit, the best I could figure out is that it seems to be a critical mass of R packages across bioconda and conda-forge that cause the issue. Here's an example:

```yaml
# Works
channels:
  - bioconda
  - conda-forge
dependencies:
  - bioconductor-tximport
  - r-rmarkdown
  - pandoc
  - r-readr
  - r-dt
```

```yaml
# Works
channels:
  - bioconda
  - conda-forge
dependencies:
  - bioconductor-tximport
  - r-rmarkdown
  - pandoc
  - r-readr
  - r-dt

  # added r-knitr
  - r-knitr
```

```yaml
# Hangs on "Solving package specifications: .", killed after 6 min
channels:
  - bioconda
  - conda-forge
dependencies:
  - bioconductor-tximport
  - r-rmarkdown
  - pandoc
  - r-readr
  - r-dt
  - r-knitr

  # added r-pheatmap
  - r-pheatmap
```
From that last one, the output from `conda env create -n tmp --file env.yml -vv` is [here](https://github.com/conda/conda/files/1079036/log.txt). And my `conda info` is:

```
Current conda install:

               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : 2.0.7
         python version : 3.5.2.final.0
       requests version : 2.17.3
       root environment : /home/ryan/miniconda3  (writable)
    default environment : /home/ryan/miniconda3
       envs directories : /home/ryan/miniconda3/envs
                          /home/ryan/.conda/envs
          package cache : /home/ryan/miniconda3/pkgs
                          /home/ryan/.conda/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/lcdb/linux-64
                          https://conda.anaconda.org/lcdb/noarch
            config file : /home/ryan/.condarc
             netrc file : /home/ryan/.netrc
           offline mode : False
             user-agent : conda/4.3.21 requests/2.17.3 CPython/3.5.2 Linux/3.13.0-119-generic debian/jessie/sid glibc/2.19
                UID:GID : 1000:1000
```
