### ISSUE TITLE
Solver *really* bad error message

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#5570]
I've tried to build a tensorflow package for python 3.6 and AFAICT I've done everything right but when I try to install it I get an UnsatisfiableError
```
λ conda install --override-channels -c dhirschfeld tensorflow=1.2.0=py36_0
Fetching package metadata ...............................
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - tensorflow 1.2.0 py36_0
Use "conda info <package>" to see the dependencies for each package.
```
The error message makes no sense to me - you need more than one package for there to be any conflicts??!! How can you have a package in conflict with itself?!
The `repodata.json` specifies the deps as:
```
    "tensorflow-1.2.0-py36_0.tar.bz2": {
      "build": "py36_0",
      "build_number": 0,
      "depends": [
        "bleach >=1.5.0",
        "html5lib >=0.999999999",
        "markdown >=2.2.0",
        "numpy >=1.11.0",
        "protobuf >=3.3.0",
        "python 3.6*",
        "six >=1.10.0",
        "werkzeug >=0.11.10"
      ],
      "license": "Apache-2.0",
      "md5": "bdca4c52652edbe0582a2c4b5e79b94b",
      "name": "tensorflow",
      "sig": null,
      "size": 22078353,
      "subdir": "win-64",
      "version": "1.2.0"
    }
```
I've gone through every dep and checked that there is a version which matches the spec available so I can't see what the problem is.

I'm sure there probably is a problem somewhere but the error message appears nonsensical to me!

Am I missing something obvious? Or is this a bug in conda?

**Comment by dhirschfeld** [comment]
**`meta.yaml`**
```yaml
package:
  name: tensorflow
  version: "1.2.0"

requirements:
  build:
    - python 3.6*
    - setuptools

  run:
    - python 3.6*
    - numpy >=1.11.0
    - six >=1.10.0
    - protobuf >=3.3.0
    - werkzeug >=0.11.10
    - html5lib >=0.999999999
    - markdown >=2.2.0
    - bleach >=1.5.0

test:
  # Python imports
  imports:
    - tensorflow

about:
  home: https://github.com/tensorflow/tensorflow
  license: Apache-2.0
  summary: "Computation using data flow graphs for scalable machine learning
```
**`bld.bat`**
```
pip install --no-deps tensorflow==1.2.0
if errorlevel 1 exit 1
sed -i 's/from backports import weakref/import weakref/g' "%SP_DIR%\tensorflow\python\util\tf_should_use.py"
if errorlevel 1 exit 1
```
