### ISSUE TITLE
conda install does not pick latest development builds from anaconda

### ISSUE THREAD

**Issue by rmancy-smg** [conda/conda#5675]
Part of my workflow revolves around frequently uploading to anaconda and then downloading and installing development builds.

Following (at least, AFAICT) PEP440 I've starting naming these packages `<name>-X.Y-devN`.
Running  `conda install` on this package name without specifying version seems to pickup the older version (i.e the one with the lower value for N).

This is what the relevant section of meta.yaml file looks like (I was previously using only 'GIT_BUILD_STR' in the `string` section but removed it as PEP440 advises against using the commit sha):

```
package:
  name: <package-name>
  version: {{GIT_DESCRIBE_TAG}}

build:
  version: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
{% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}
  string:
{% else %}
  string: dev{{ environ.get('GIT_DESCRIBE_NUMBER', '') }}
{% endif %}
```

The output of `conda info`

```
Current conda install:

               platform : linux-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : 2.1.15
         python version : 3.5.3.final.0
       requests version : 2.14.2
```
