### ISSUE TITLE
conda env processing to provide more helpful messages

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#5885]
From the Anaconda ML (see last half of [this thread](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/oNZzhJKwA9g) ) :

> I have my yml file at place the file looks like this:
> ls ps-env shows the file

```yaml
name: ps-env
dependecies:
  - python = 3.5.2
  - pandas = 0.17.1
  - numpy = 1.13.1
  - sklearn = 0.19.0
  - scipy = 0.19.1
  - tensorflow
  - keras
  - imbalanced-learn
```

> I still get the error. It doesnt make sense to me

Can you spot the problem?  I tried myself, putting that YAML into a file `testml.yaml`, and got:

```
$ conda env create --file testml.yaml 
Using Anaconda API: https://api.anaconda.org

SpecNotFound: Can't process without a name
```

Someone on the ML pointed out the issue: spelling mistake in the YAML.  I'd suggest a few things:

* improve the error message to say something like:

    ```
    "dependencies" section not found, unable to create conda environment
    ```

* report any sections that are found that are unexpected and are going to be ignored (such as `dependecies`

* use something like Kwalify (and perhaps [pykwalify](https://github.com/Grokzen/pykwalify) ) to test/assert an open schema on the JSON for env files
