### ISSUE TITLE
Package sizes differ

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#5957]
Please compare [log 1]( https://ci.appveyor.com/project/conda-forge/jupyter-kernel-gateway-feedstock/build/1.0.19/job/5s6lra5xdjm4583d#L19 ) and [log 2]( https://ci.appveyor.com/project/conda-forge/libsass-feedstock/build/1.0.1/job/x6huy0ggr8p2ytwp#L19 ) lines 21-34 in both. Seems there are a few packages in there with different sizes (e.g. `cryptography`) even though they appear to be the same package in both cases.

**Comment by kalefranz** [comment]
It looks like this might just be `win-32` vs `win-64`?

```
openssl-1.0.2l-vc14_0.tar.bz2:
  win-32: 3.98 MB
  win-64: 5.12 MB

cryptography-1.8.1-py35_0.tar.bz2:
  win-32: 300.1 KB
  win-64: 352.1 KB
```
