### ISSUE TITLE
When use conda create environment the extra packages will be installed

### ISSUE THREAD

**Issue by Drake-Z** [conda/conda#6067]
I'm new to conda, Today i install the Anaconda3, I try to use conda create a python environment with only standard library modules, and a few packages like pip, wheel.

I Running:

`conda create -n test python=3.6`

Get the following result:

````
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment D:\Anaconda3\envs\test:

The following NEW packages will be INSTALLED:

    asn1crypto:      0.22.0-py36h8e79faa_1      defaults
    ca-certificates: 2017.08.26-h94faf87_0      defaults
    cachecontrol:    0.12.3-py36hfe50d7b_0      defaults
    certifi:         2017.7.27.1-py36h043bc9e_0 defaults
    cffi:            1.10.0-py36hae3d1b5_1      defaults
    chardet:         3.0.4-py36h420ce6e_1       defaults
    colorama:        0.3.9-py36h029ae33_0       defaults
    cryptography:    2.0.3-py36h123decb_1       defaults
    distlib:         0.2.5-py36h51371be_0       defaults
    html5lib:        0.999999999-py36ha09b1f3_0 defaults
    idna:            2.6-py36h148d497_1         defaults
    lockfile:        0.12.2-py36h0468280_0      defaults
    msgpack-python:  0.4.8-py36h58b1e9d_0       defaults
    openssl:         1.0.2l-vc14hcac20b0_2      defaults [vc14]
    packaging:       16.8-py36ha0986f6_1        defaults
    pip:             9.0.1-py36hadba87b_3       defaults
    progress:        1.3-py36hbeca8d3_0         defaults
    pycparser:       2.18-py36hd053e01_1        defaults
    pyopenssl:       17.2.0-py36h15ca2fc_0      defaults
    pyparsing:       2.2.0-py36h785a196_1       defaults
    pysocks:         1.6.7-py36h698d350_1       defaults
    python:          3.6.2-h09676a0_15          defaults
    requests:        2.18.4-py36h4371aae_1      defaults
    setuptools:      36.5.0-py36h65f9e6e_0      defaults
    six:             1.10.0-py36h2c0fdd8_1      defaults
    urllib3:         1.22-py36h276f60a_0        defaults
    vc:              14-h2379b0c_1              defaults
    vs2015_runtime:  14.0.25123-hd4c4e62_1      defaults
    webencodings:    0.5.1-py36h67c50ae_1       defaults
    wheel:           0.29.0-py36h6ce6cde_1      defaults
    win_inet_pton:   1.0.1-py36he67d7fd_1       defaults
    wincertstore:    0.2-py36h7fe50ca_0         defaults

Proceed ([y]/n)?
````
Some extra package show in the list of "Package plan for installation in environment",  which is unexpect and useless to me, like html5lib, webencodings, msgpack-python

It always show will install these packages when create 2.7, 3.5 or 3.6 version of python environment.

But when create other version of python environment, like 3.4, 3.3, 2.6:

`conda create -n test python=3.4`

The result is what i want, just a few packages:
````
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment D:\Anaconda3\envs\test:

The following NEW packages will be INSTALLED:

    pip:            9.0.1-py34_1    defaults
    python:         3.4.5-0         defaults
    setuptools:     27.2.0-py34_1   defaults
    vs2010_runtime: 10.00.40219.1-2 defaults
    wheel:          0.29.0-py34_0   defaults
unintuition
Proceed ([y]/n)?
````
So why it's different when use same option create environment of  python between 3.6/3.5/2.7 and other versions?

How can i get the simple python environment of python3.6 or 2.7 without unnecessary packages?

Current conda info:
````
               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.22
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : D:\Anaconda3  (writable)
    default environment : D:\Anaconda3
       envs directories : D:\Anaconda3\envs
                          C:\Users\Drake\AppData\Local\conda\conda\envs
                          C:\Users\Drake\.conda\envs
          package cache : D:\Anaconda3\pkgs
                          C:\Users\Drake\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Drake\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Windows/10 Windows/10.0.14393
          administrator : False
```

**Comment by kalefranz** [comment]
Could you provide the output of `conda config --show` and `conda config --show-sources` ?

**Comment by Drake-Z** [comment]
output of `conda config --show` :
```
add_anaconda_token: True
add_pip_as_python_dependency: True
allow_non_channel_urls: True
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: False
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  pkgs/main: https://repo.continuum.io/
  pkgs/free: https://repo.continuum.io/
  pkgs/r: https://repo.continuum.io/
  pkgs/pro: https://repo.continuum.io/
  pkgs/msys2: https://repo.continuum.io/
custom_multichannels:
  defaults: ["https://repo.continuum.io/pkgs/main", "https://repo.continuum.io/pkgs/free", "https://repo.continuum.io/pkgs/r", "https://repo.cont
inuum.io/pkgs/pro", "https://repo.continuum.io/pkgs/msys2"]
  local: []
default_channels:
  - https://repo.continuum.io/pkgs/main
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
  - https://repo.continuum.io/pkgs/msys2
disallow: []
envs_dirs:
  - D:\Anaconda3\envs
  - C:\Users\Drake\AppData\Local\conda\conda\envs
  - C:\Users\Drake\.conda\envs
force: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
non_admin_enabled: True
offline: False
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - D:\Anaconda3\pkgs
  - C:\Users\Drake\AppData\Local\conda\conda\pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
rollback_enabled: True
shortcuts: True
show_channel_urls: True
ssl_verify: True
track_features: []
use_pip: True
verbosity: 0
```
output of `conda config --show-sources`
```
==> C:\Users\Drake\.condarc <==
ssl_verify: True
channels:
  - defaults
show_channel_urls: True
```
PS: I read documentation and find a littel complex way from to create environment:
use --file environment.txt, which environment.txt content is:
```
@EXPLICIT
https://repo.continuum.io/pkgs/free/win-64/pip-9.0.1-py36_1.tar.bz2
```
(if i use .yml file still get same result as above, so i can only use @EXPLICIT)
Finally get it.
And i found even create simple python environment, if use conda install (any pkg) in new environment, it still will install those deafult packages which not setup yet. so i can only use pip.
