### ISSUE TITLE
conflicts

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#608]
There should be a way in the metadata to specify conflicts, i.e., specs that cannot be installed at the same time. It will be trivial to add this to the solver. There is already a flag for this in the meta.yaml spec for conda build.

**Comment by jchodera** [comment]
This would be great for having dev packages conflict with non-dev packages.

Any progress on this?

**Comment by kalefranz** [comment]
Just tagged with Solver. It's a topic that needs a deep dive. We'll make sure this use case is part of the consideration.

**Comment by mcg1969** [comment]
@asmeurer @kalefranz optional dependencies would allow us to do this now. If package A conflicts with package B, give A an optional dependency `B @ @ [optional=True]` and B an optional dependency `A @ @ [optional=True]`.

Of course, having an explicit `conflicts` keyword would clean that up nicely.

**Comment by mcg1969** [comment]
To clarify, this would work with whatever versions of conda and conda-build support the new optional dependency functionality.

**Comment by asmeurer** [comment]
What does @ @ mean?

**Comment by rainwoodman** [comment]
I heard that the mpich2 package from anaconda shall be deprecated, so we need a way to mark it as a 'decprecated conflict' yielding the way for the newer package (mpich which is mpich-3.x). 

In RPM I recall you are allowed to claim that a package deprecates another package.  

Would the `@ @` magic help in this case -- and what does  `@ @` mean anyways?

**Comment by mingwandroid** [comment]
You didn't really hear it from me, you heard it from [here](https://github.com/ContinuumIO/anaconda-recipes/pull/129#issuecomment-337147043), we just follow expert advice in these regards (I know very little about MPI).

When I say we should deprecate it I do not mean that we should do *anything* regarding changing legacy packages that identify it as a dependency.

What I mean is that future packages and future versions of existing packages should replace any declared `mpich2` dependency with `mpich` when they are rebuilt.

So this is not related to any conda concept of `conflict` or this `@` stuff.

**Comment by rainwoodman** [comment]
mpich and mpich2 are conflict in the sense that mpich and mpich2 writes to the same files. So if I install mpich2 and mpich at the same time, one of them is broken (depending on which one is installed first). My understanding is that conflict means 'cannot coexist'. Deprecation means 'functionality replacement'. Is it related to conflict or @ stuff after taking this into consideration?

**Comment by rainwoodman** [comment]
@mcg1969 could you elaborate a bit about your `A @ @` and `B @ @` method. I tried it couldn't get it to work.

I am basically trying to provide binaries for two incompatible hosts (edison and cori). I'd like to be able to select which binary to use by pinning the packages to these two 'meta' packages; thus they shall be made mutually exclusive. 

Here are my meta.yaml files of the two conflicting packages, using the optional + `@ @` trick:

Package 1:
```
{% set build = 0 %}
{% set version = '0.0.0' %}
{% set major = version.rpartition('.')[0] %}

package:
    name: cori-prgenv-gnu_linux-64
    version: {{ version }}

build:
    number: {{ build }}
    skip: True  # [win]
    skip: True  # [osx]

requirements:
    conflicts:
        - edison-prgenv-gnu_linux-64
    run_constrained:
        - edison-prgenv-gnu_linux-64 @ @

run_exports:
    # impose this requirement across the build/host boundary
    strong:
        - cori-prgenv-gnu_linux-64
   
```
Package 2:
```
{% set build = 0 %}
{% set version = '0.0.0' %}
{% set major = version.rpartition('.')[0] %}

package:
    name: edison-prgenv-gnu_linux-64
    version: {{ version }}

build:
    number: {{ build }}
    skip: True  # [win]
    skip: True  # [osx]


requirements:
    conflicts:
        - cori-prgenv-gnu_linux-64
    run_constrained:
        - cori-prgenv-gnu_linux-64 @ @


run_exports:
    # impose this requirement across the build/host boundary
    strong:
        - edison-prgenv-gnu_linux-64

```

Then if I create an environment with 
```
conda create -n test36 cori-prgenv-gnu_linux-64
```
and running
```
conda install -n test36 edison-prgenv-gnu_linux64
```
allows me to install both packages at the same time. 

Looks like neither the conflict keyword or the `@ @` hack worked. Did I do something wrong or is this not yet supposed to work? My conda version is 

```
               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4

```
