### ISSUE TITLE
cannot track feature on OS X

### ISSUE THREAD

**Issue by fvisconti** [conda/conda#6141]
I have a metapackage named `dev`, created with this simple `meta.yaml` file:
```
package:
  name: dev
  version: 1.0

build:
  noarch: generic
  track_features:
    - dev
```

Now, my software has a version for linux, another for OS X: if I want the dev feature on a linux box, everything works fine.
But if I try and get the feature version on OS X, it ignores the _feature_ version of the software.

The packages are organised in a private channel, with three subdir:
- linux-64
- osx-64
- noarch

The metapackage is in the noarch subdir, while the software packages are in their directories. 

Here they are the `meta.yaml` files for Linux (first) and OS X:

------------
Linux meta:
```
package:
  name: XXX
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: URL
  git_rev: develop

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ GIT_BUILD_STR }}
  binary_relocation: False
  include_recipe: False
  features:
    - dev

requirements:
  build:
    - python ==3.5
    - heasoft >=6.19
  run:
    - python ==3.5
    - pymysql 0.7.9
    - astropy 1.3.2
    - matplotlib 2.0.0
    - numpy 1.12.1
    - scipy 0.19.0
    - heasoft >=6.19
    - confuse 0.4.0
    - readline 6.2 3
```
----------
OS X meta:

```
package:
  name: XXX
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: URL
  git_rev: develop

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ GIT_BUILD_STR }}
  binary_relocation: False
  include_recipe: False
  features:
    - dev

requirements:
  build:
    - python >=3.5
    - heasoft >=6.19
  run:
    - python >=3.5
    - pymysql 0.7.9
    - astropy 1.3.2
    - matplotlib 2.0.0
    - numpy 1.12.1
    - scipy 0.19.0
    - heasoft >=6.19
    - confuse 0.4.0
    - readline 6.2 3
```

What am I missing?
