### ISSUE TITLE
Error while installing packages from conda-forge or other channels

### ISSUE THREAD

**Issue by pyousefi** [conda/conda#6198]
I'm at a loss:

`C:\windows\system32>conda install -c anaconda terminado
`

```
WARNING: The remote server could not find the noarch directory for the requested channel with url: https://pypi.python.org/pypi

It is possible you have given conda an invalid channel. Please double-check your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that the channel administrator create `noarch/repodata.json` and associated `noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
...........

PackageNotFoundError: Packages missing in current channels:

  - terminado

We have searched for the packages in the following channels:

  - https://conda.anaconda.org/anaconda/win-64
  - https://conda.anaconda.org/anaconda/noarch
  - https://pypi.python.org/pypi/win-64
  - https://pypi.python.org/pypi/noarch
  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch



C:\windows\system32>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\tools\Anaconda3  (writable)
    default environment : C:\tools\Anaconda3
       envs directories : C:\tools\Anaconda3\envs
                          C:\Users\pyousefi\AppData\Local\conda\conda\envs
                          C:\Users\pyousefi\.conda\envs
          package cache : C:\tools\Anaconda3\pkgs
                          C:\Users\pyousefi\AppData\Local\conda\conda\pkgs
           channel URLs : https://pypi.python.org/pypi/win-64
                          https://pypi.python.org/pypi/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\pyousefi\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.14.2 CPython/3.6.1 Windows/7 Windows/6.1.7601
          administrator : True

C:\windows\system32>conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
allow_non_channel_urls: True
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: False
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - https://pypi.python.org/pypi
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  pkgs/main: https://repo.continuum.io/
  pkgs/free: https://repo.continuum.io/
  pkgs/r: https://repo.continuum.io/
  pkgs/pro: https://repo.continuum.io/
  pkgs/msys2: https://repo.continuum.io/
custom_multichannels:
  defaults: ["https://repo.continuum.io/pkgs/main", "https://repo.continuum.io/p
kgs/free", "https://repo.continuum.io/pkgs/r", "https://repo.continuum.io/pkgs/p
ro", "https://repo.continuum.io/pkgs/msys2"]
  local: []
default_channels:
  - https://repo.continuum.io/pkgs/main
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
  - https://repo.continuum.io/pkgs/msys2
disallow: []
envs_dirs:
  - C:\tools\Anaconda3\envs
  - C:\Users\pyousefi\AppData\Local\conda\conda\envs
  - C:\Users\pyousefi\.conda\envs
force: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
non_admin_enabled: True
offline: False
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - C:\tools\Anaconda3\pkgs
  - C:\Users\pyousefi\AppData\Local\conda\conda\pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
rollback_enabled: True
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
use_pip: True
verbosity: 0
```

**Comment by kalefranz** [comment]
I thought this was fixed.  Can you confirm this just happened to you, and not a couple days ago?

**Comment by pyousefi** [comment]
Yes, we can do a screenshare...

**Comment by kalefranz** [comment]
This probably will probably take care of itself for you if you do `anaconda logout` and then `anaconda login`.

**Comment by pyousefi** [comment]
Cool!
I'm in Paris and will try first thing tomorrow morning.

**Comment by chaturv3di** [comment]
I'm glad to find this issue still open. This is happening to me right now, even though I've seen a [previous issue](https://github.com/conda/conda/issues/5761) related to this which was closed.

```
$ conda info

     active environment : None
       user config file : /Users/namit/.condarc
 populated config files : /Users/namit/.condarc
          conda version : 4.4.4
    conda-build version : 1.21.3
         python version : 3.5.2.final.0
       base environment : //anaconda  (writable)
           channel URLs : https://conda.anaconda.org/anaconda/osx-64
                          https://conda.anaconda.org/anaconda/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : //anaconda/pkgs
                          /Users/namit/.conda/pkgs
       envs directories : //anaconda/envs
                          /Users/namit/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.4 requests/2.14.2 CPython/3.5.2 Darwin/17.3.0 OSX/10.13.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
And

```
$ conda config --show

add_anaconda_token: True
add_pip_as_python_dependency: True
aggressive_update_packages:
  - ca-certificates
  - certifi
  - openssl
allow_non_channel_urls: True
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: None
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - anaconda
  - conda-forge
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  pkgs/pro: https://repo.continuum.io/
  pkgs/main: https://repo.continuum.io/
  pkgs/r: https://repo.continuum.io/
  pkgs/free: https://repo.continuum.io/
custom_multichannels:
  defaults: ["https://repo.continuum.io/pkgs/main", "https://repo.continuum.io/pkgs/free", "https://repo.continuum.io/pkgs/r", "https://repo.continuum.io/pkgs/pro"]
  local: []
default_channels:
  - https://repo.continuum.io/pkgs/main
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
disallow: []
download_only: False
envs_dirs:
  - //anaconda/envs
  - /Users/namit/.conda/envs
force: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
no_dependencies: False
non_admin_enabled: True
notify_outdated_conda: True
offline: False
override_channels_enabled: True
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - //anaconda/pkgs
  - /Users/namit/.conda/pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
report_errors: None
rollback_enabled: True
safety_checks: warn
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
use_index_cache: False
use_pip: True
verbosity: 0
whitelist_channels: []
```

Nevertheless, I can still install packages. E.g. `python-graphviz`. Although, note in the end that it installs an older version `v0.5.2`, whereas the [latest version](https://anaconda.org/conda-forge/python-graphviz) is `v0.8.1`. 

```
$ conda install -c conda-forge python-graphviz

Solving environment: - 
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/conda-forge

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
/ 
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/anaconda

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
done

## Package Plan ##

  environment location: //anaconda

  added / updated specs: 
    - python-graphviz


The following NEW packages will be INSTALLED:

    graphviz:        2.38.0-3    
    python-graphviz: 0.5.2-py35_0

Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

I don't know from where `conda` is pulling these packages. Unlike @pyousefi, I don't have an account on anaconda cloud, so logging out and back is not viable.

Thanks in advance.

**Comment by nehaljwani** [comment]
@chaturv3di Could you share the output for: `conda list -ec` after installing that old package?

**Comment by chaturv3di** [comment]
The output contains 179 entries. I'll just post the relevant info.
```
$ conda list -ec | grep graphviz

defaults::graphviz-2.38.0-3
defaults::python-graphviz-0.5.2-py35_0
```

**Comment by kalefranz** [comment]
Was anybody ever able to figure out anything new about what's going on here?

**Comment by JCCPort** [comment]
I'm having the same issue, interested in an update as well.

**Comment by pyousefi** [comment]
I moved from the windows laptop that was causing this to a mac. No longer an issue for me.

**Comment by waficf** [comment]
Having same error as I cannot add packages using conda in Terminal for the new anaconda 4.5.
I checked case #[6734](https://github.com/conda/conda/issues/6734) and this one here but failed to get a proper solution.
I also tried the [stackoverflow](https://stackoverflow.com/questions/48101882/warning-the-remote-server-could-not-find-the-noarch-directory-for-the-requested) solution with no luck.

> conda config --show

```
add_anaconda_token: True
add_pip_as_python_dependency: True
aggressive_update_packages:
  - ca-certificates
  - certifi
  - openssl
allow_non_channel_urls: False
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: None
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - conda-forge
  - py3
  - anaconda-fusion
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  pkgs/main: https://repo.anaconda.com
  pkgs/free: https://repo.anaconda.com
  pkgs/r: https://repo.anaconda.com
  pkgs/pro: https://repo.anaconda.com
custom_multichannels:
  defaults: ["https://repo.anaconda.com/pkgs/main", "https://repo.anaconda.com/pkgs/free", "https://repo.anaconda.com/pkgs/r", "https://repo.anaconda.com/pkgs/pro"]
  local: []
default_channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/free
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/pro
disallowed_packages: []
download_only: False
envs_dirs:
  - /anaconda3/envs
  - /Users/wafic/.conda/envs
force: False
json: False
local_repodata_ttl: 1
max_shlvl: 2
migrated_channel_aliases: []
no_dependencies: False
non_admin_enabled: True
notify_outdated_conda: True
offline: False
override_channels_enabled: True
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - /anaconda3/pkgs
  - /Users/wafic/.conda/pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
report_errors: None
rollback_enabled: True
safety_checks: warn
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
use_index_cache: False
use_pip: True
verbosity: 0
whitelist_channels: []
```
