### ISSUE TITLE
Channel pins in "environment.yaml" files are not saved to package specs

### ISSUE THREAD

**Issue by sdvillal** [conda/conda#6385]
Channel pins specified in environment files are not respected.  For example,run ```conda env create``` with this environment file:

```yaml
name: channel-not-written-to-user-specs

dependencies:
  - defaults::six
```

If we look at conda-meta/six*.json we can see that the channel pin has not been added to specs. Where we should read ```"requested_spec": "defaults::six"```, we only find ```"requested_spec": "six"```.

This is with conda 4.4.0rc2.
