### ISSUE TITLE
FullyQualifiedError with Miniconda 4.4.6 on Windows

### ISSUE THREAD

**Issue by tgsmith61591** [conda/conda#6666]
I've been using Miniconda in my Appveyor builds. Recently they started breaking when using Conda 4.4.6. Here's the stack trace I'm getting:

```
conda create -n testenv --yes python=$env:PYTHON_VERSION numpy scipy cython scikit-learn statsmodels pip nose patsy
Solving environment: ...working... done
conda : 
At line:1 char:1
+ conda create -n testenv --yes python=$env:PYTHON_VERSION numpy scipy  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

Here's a link to an Appveyor log showing where things break: https://ci.appveyor.com/project/tgsmith61591/pyramid/build/1.0.145/job/5mhhg33x86vuh9rc

And here is the relevant segment of the `appveyor.yml` in question:

```yml
environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script interpreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\build_tools\\appveyor\\run_with_env.cmd"

  matrix:
    - PY_MAJOR_VER: 2
      PYTHON_ARCH: "x86"
      PYTHON_VERSION: "2.7"

    - PY_MAJOR_VER: 2
      PYTHON_ARCH: "x86_64"
      PYTHON_VERSION: "2.7"

    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86"
      PYTHON_VERSION: "3.5"

    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86_64"
      PYTHON_VERSION: "3.5"

build_script:
  - ps: Start-FileDownload "https://repo.continuum.io/miniconda/Miniconda$env:PY_MAJOR_VER-latest-Windows-$env:PYTHON_ARCH.exe" C:\Miniconda.exe; echo "Finished downloading miniconda"
  - cmd: C:\Miniconda.exe /S /D=C:\Py
  - SET PATH=C:\Py;C:\Py\Scripts;C:\Py\Library\bin;%PATH%
  - conda config --set always_yes yes
  - conda update conda

  # Debugging because Appveyor gives us no stack traces when this stuff breaks.
  - ps: echo "Conda version:"
  - conda --version
  - ps: echo "Python version=$env:PYTHON_VERSION"

  # Things we'll need for build/test
  - ps: conda create -n testenv --yes python=$env:PYTHON_VERSION numpy scipy cython scikit-learn statsmodels pip nose patsy
  - activate testenv

  # Things we'll need for deployment
  - pip install wheel twine

  # Build the package
  - python setup.py develop
```

__Note__ that if I comment out this line it all works:

```
# - conda update conda
```

A working build (same exact build but without the update line) on Conda 4.3.31: https://ci.appveyor.com/project/tgsmith61591/pyramid/build/1.0.146/job/9pvlsmwdv6vxfhn8
