### ISSUE TITLE
Allow pip install flags to be recognized in environment files

### ISSUE THREAD

**Issue by eyadsibai** [conda/conda#6805]
## Current Behavior

if I have in the environment.yaml file under pip section
`package --no-deps` as an example it does not recognize the flag. it only recognizes the general flags not the specific ones for `pip install`

## Expected Behavior

I should be able to add `pip install` flags

**Comment by kalefranz** [comment]
What version of conda are you using?  I thought we had already added this.

**Comment by kalefranz** [comment]
https://github.com/conda/conda/pull/3969

**Comment by eyadsibai** [comment]
I'm using the latest version.

**Comment by kalefranz** [comment]
Then please give more details. Give me an environment.yml file with instructions demonstrating what you want to happen.

**Comment by eyadsibai** [comment]
what happens right now 
```
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Usage: pip [options]

pip: error: no such option: --no-deps


CondaValueError: pip returned an error
```

pip install --help
```
Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

Description:
  Install packages from:
  
  - PyPI (and other indexes) using requirement specifiers.
  - VCS project urls.
  - Local project directories.
  - Local or remote source archives.
  
  pip also supports installing from "requirements files", which provide
  an easy way to specify a whole environment to be installed.

Install Options:
  -c, --constraint <file>     Constrain versions using the given constraints file. This option can be used multiple times.
  -e, --editable <path/url>   Install a project in editable mode (i.e. setuptools "develop mode") from a local project path or a VCS url.
  -r, --requirement <file>    Install from the given requirements file. This option can be used multiple times.
  -b, --build <dir>           Directory to unpack packages into and build in.
  -t, --target <dir>          Install packages into <dir>. By default this will not replace existing files/folders in <dir>. Use --upgrade to replace existing packages in <dir> with new versions.
  -d, --download <dir>        Download packages into <dir> instead of installing them, regardless of what's already installed.
  --src <dir>                 Directory to check out editable projects into. The default in a virtualenv is "<venv path>/src". The default for global installs is "<current dir>/src".
  -U, --upgrade               Upgrade all specified packages to the newest available version. The handling of dependencies depends on the upgrade-strategy used.
  --upgrade-strategy <upgrade_strategy>
                              Determines how dependency upgrading should be handled. "eager" - dependencies are upgraded regardless of whether the currently installed version satisfies the requirements of the upgraded package(s). "only-
                              if-needed" -  are upgraded only when they do not satisfy the requirements of the upgraded package(s).
  --force-reinstall           When upgrading, reinstall all packages even if they are already up-to-date.
  -I, --ignore-installed      Ignore the installed packages (reinstalling instead).
  --ignore-requires-python    Ignore the Requires-Python information.
  --no-deps                   Don't install package dependencies.
  --install-option <options>  Extra arguments to be supplied to the setup.py install command (use like --install-option="--install-scripts=/usr/local/bin"). Use multiple --install-option options to pass multiple options to setup.py
                              install. If you are using an option with a directory path, be sure to use absolute path.
  --global-option <options>   Extra global options to be supplied to the setup.py call before the install command.
  --user                      Install to the Python user install directory for your platform. Typically ~/.local/, or %APPDATA%\Python on Windows. (See the Python documentation for site.USER_BASE for full details.)
  --egg                       Install packages as eggs, not 'flat', like pip normally does. This option is not about installing *from* eggs. (WARNING: Because this option overrides pip's normal install logic, requirements files may not
                              behave as expected.)
  --root <dir>                Install everything relative to this alternate root directory.
  --prefix <dir>              Installation prefix where lib, bin and other top-level folders are placed
  --compile                   Compile py files to pyc
  --no-compile                Do not compile py files to pyc
  --no-use-wheel              Do not Find and prefer wheel archives when searching indexes and find-links locations. DEPRECATED in favour of --no-binary.
  --no-binary <format_control>
                              Do not use binary packages. Can be supplied multiple times, and each time adds to the existing value. Accepts either :all: to disable all binary packages, :none: to empty the set, or one or more package
                              names with commas between them. Note that some packages are tricky to compile and may fail to install when this option is used on them.
  --only-binary <format_control>
                              Do not use source packages. Can be supplied multiple times, and each time adds to the existing value. Accepts either :all: to disable all source packages, :none: to empty the set, or one or more package
                              names with commas between them. Packages without binary distributions will fail to install when this option is used on them.
  --pre                       Include pre-release and development versions. By default, pip only finds stable versions.
  --no-clean                  Don't clean up build directories.
  --require-hashes            Require a hash to check each requirement against, for repeatable installs. This option is implied when any package in a requirements file has a --hash option.

Package Index Options (including deprecated options):
  -i, --index-url <url>       Base URL of Python Package Index (default https://pypi.python.org/simple). This should point to a repository compliant with PEP 503 (the simple repository API) or a local directory laid out in the same
                              format.
  --extra-index-url <url>     Extra URLs of package indexes to use in addition to --index-url. Should follow the same rules as --index-url.
  --no-index                  Ignore package index (only looking at --find-links URLs instead).
  -f, --find-links <url>      If a url or path to an html file, then parse for links to archives. If a local path or file:// url that's a directory, then look for archives in the directory listing.
  --process-dependency-links  Enable the processing of dependency links.

General Options:
  -h, --help                  Show help.
  --isolated                  Run pip in an isolated mode, ignoring environment variables and user configuration.
  -v, --verbose               Give more output. Option is additive, and can be used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output. Option is additive, and can be used up to 3 times (corresponding to WARNING, ERROR, and CRITICAL logging levels).
  --log <path>                Path to a verbose appending log.
  --proxy <proxy>             Specify a proxy in the form [user:passwd@]proxy.server:port.
  --retries <retries>         Maximum number of retries each connection should attempt (default 5 times).
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists: (s)witch, (i)gnore, (w)ipe, (b)ackup, (a)bort.
  --trusted-host <hostname>   Mark this host as trusted, even though it does not have valid or any HTTPS.
  --cert <path>               Path to alternate CA bundle.
  --client-cert <path>        Path to SSL client certificate, a single file containing the private key and the certificate in PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine whether a new version of pip is available for download. Implied with --no-index.
```
we can see that --no-deps is one of the flags for `pip install`

my environment file 
```
name: test2
channels:
  - conda-forge
  - glemaitre
  - maciejkula
  - ioam
  - defaults
  - pkgw-forge
  - datamicroscopes
  - distributions

dependencies:
  - python=3.6
  - pip>=9.0
  - pandas>=0.22.0

  - pip:
    - disp
    - kaggle-cli
    - lifetimes
    - git+https://github.com/tmadl/semisup-learn --no-deps 
```

**Comment by eyadsibai** [comment]
same issue

**Comment by sdvillal** [comment]
This is not a limitation specific to conda. You cannot do that either with pip requirements.txt files, which is what conda uses behind the scenes. We can get kinda close by using [per requirement overrides](https://pip.pypa.io/en/stable/reference/pip_install/#per-requirement-overrides):

```yaml
- pip:
  - disp
  - kaggle-cli
  - lifetimes
  - git+https://github.com/tmadl/semisup-learn --install-option="--no-deps"
```

But I do not think that is really advisable: it is going to run setup.py directly, ignoring wheels and trying to compile a lot of stuff.

How would you do this with pip? As far as I know, there there is no way to apply "--no-deps" for some dependencies but not for others on the same call. You would call pip twice:

```sh
# Calling pip install with a list of dependencies in the CLI, twice
pip install disp kaglle-cli lifetimes
pip install --no-deps git+https://github.com/tmadl/semisup-learn

# Or equivalently, have two requirements files
pip install -r deps_with_deps.txt
pip install --no-deps -r deps_without_deps.txt
```

If we want to support this in conda environment files, we need to come up with a mechanism to specify flags for pip and invoke pip as many times as different flags exist. One possible syntax and example:

```yaml
- pip:
- pip:
  # Install these normally
  - disp
  - kaggle-cli
  # From now on, we will install with --no-deps and clone to some dir
  - [--no-deps, --src, some_dir]
  - git+https://github.com/tmadl/semisup-learn --no-deps
  - lifetimes  # Beware --no-deps apply also to lifetimes!
  # Keep installing without special options
  - []
  - six
  # Again no deps
  - [--no-deps]
  - argh
```

Then we would slightly modify [the pip installer code](https://github.com/conda/conda/blob/7cb5f66dd46727ce8f16b969e084555e6221cfc5/conda_env/installers/pip.py) accordingly. Something like this (beware, written directly here and untested):

```python

from __future__ import absolute_import

import os
import os.path as op
import subprocess
import tempfile
from conda_env.pip_util import pip_args
from conda.exceptions import CondaValueError

def _group_dependencies_by_pip_options_and_install(prefix, specs, args, *_, **kwargs):
    current_pip_options = []
    current_spec_group = []
    for spec in specs:
        if isinstance(spec, list):
            if current_spec_group:
                _pip_install_via_requirements(prefix, specs, args, 
                                              pip_options=current_pip_options)
            current_pip_options = spec
            current_spec_group = []
        else:
            current_spec_group.append(spec)

def _pip_install_via_requirements(prefix, specs, args, pip_options=()):
    """
    Installs the pip dependencies in specs using a temporary pip requirements file.
    Args
    ----
    prefix: string
      The path to the python and pip executables.
    specs: iterable of strings
      Each element should be a valid pip dependency.
      See: https://pip.pypa.io/en/stable/user_guide/#requirements-files
           https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format
    """
    try:
        pip_workdir = op.dirname(op.abspath(args.file))
    except AttributeError:
        pip_workdir = None
    requirements = None
    try:
        # Generate the temporary requirements file
        requirements = tempfile.NamedTemporaryFile(mode='w',
                                                   prefix='condaenv.',
                                                   suffix='.requirements.txt',
                                                   dir=pip_workdir,
                                                   delete=False)
        requirements.write('\n'.join(specs))
        requirements.close()
        # pip command line...
        args, pip_version = pip_args(prefix)
        if args is None:
            return
        pip_cmd = args + ['install'] + list(pip_options) + ['-r', requirements.name]
        # ...run it
        process = subprocess.Popen(pip_cmd,
                                   cwd=pip_workdir,
                                   universal_newlines=True)
        process.communicate()
        if process.returncode != 0:
            raise CondaValueError("pip returned an error")
    finally:
        # Win/Appveyor does not like it if we use context manager + delete=True.
        # So we delete the temporary file in a finally block.
        if requirements is not None and op.isfile(requirements.name):
            os.remove(requirements.name)

# Conform to Installers API
install = _group_dependencies_by_pip_options_and_install
```

Does that sound like a straightforward extension? If so I could open a PR (but I do not really know when I will have the time). Or feel free to implement the idea.

**Comment by kalefranz** [comment]
I wouldn't start on a PR yet.  We have tons of issues tagged https://github.com/conda/conda/labels/tag%3Aenvironment-spec, all pointing to things we know we need to rework with a holistic revisiting of `conda env` and `environment.yml`.

**Comment by hadim** [comment]
As for now, I don't use pip packages in my various Conda env.yml files because of this issue. Very often when you install a package with pip without `--no-deps` it ends up installing a new numpy/scipy version overriding the Conda provided packages.

So, for now, I just install me Conda env and then run manually the pip command.

Here is an example of my Conda env fil (for Tensorflow):

```yml
# Usqge: `conda env update -f environment.yml`
channels:
  - conda-forge

dependencies:
    - python>=3.6
    - numpy
    - scipy
    - matplotlib
    - pillow
    - scikit-image
    - scikit-learn
    - tifffile
    - scipy
    - opencv
    - pycocotools
    - tqdm
    - jupyterlab
    - pytest
    - pandas
    - pyyaml
    - pylint
    - mypy
    - importlib_resources
    - pep8
    - requests
    - ipywidgets
    # Tensorflow dependencies
    - protobuf
    - absl-py
    - gast
    - astor
    - termcolor
    - h5py
    - wrapt
    # Tensorboard dependencies
    - werkzeug
    - markdown
    - grpcio
    # Tensorflow datasets dependencies
    - promise
    - dill
    #- pip:
        # Install TF deps not available on Conda.
        #- pip install --no-deps -U keras_preprocessing keras_applications
        #- pip install --no-deps -U tensorflow-estimator tensorflow-datasets tensorflow_metadata
        # Install TF (from nightly or not).
        #- pip install --no-deps -U tensorflow==2.0.0-alpha0 tensorboard
        # or
        #- pip install --no-deps -U tensorflow-cpu==2.0.0-alpha0 tensorboard
        # or
        #- pip install --no-deps -U tf-nightly-2.0-preview tb-nightly
        # or
        #- pip install --no-deps -U tf-nightly-cpu-2.0-preview tb-nightly
```

**Comment by alghimo** [comment]
As a work-around for this issue, you can do the following:
- Put your dependencies in a requirements.txt file
- Change your environment.yml file so that it looks like this:

```yaml
- pip
   - --no-deps
   - -rrequirements.txt
```

**(the double "r" in the ```-rrequirements``` is not a typo)**

I'm using this with the ```--no-cache-dir``` option and works fine. I hope this helps :)

**Comment by eyadsibai** [comment]
@alghimo thanks. so if I need `--no-deps` for a specific package I can have it inside the `requirements.txt`

**Comment by alghimo** [comment]
@eyadsibai I think it doesn't work inside the requirements.txt (at least it didn't work for me). However, I was just trying in an environment with a more recent conda version, and it seems like the --no-cache-dir doesn't work in the more recent version I have. So, in short:

- With version ```4.3.30```, having this in the environment.yml works as expected (it passes the flag to pip install):

```yaml
  - pip:
    - --no-cache-dir
    - -rrequirements.txt
```

In version ```4.4.10```, the same environment.yml file fails with this error:

```yaml
Usage: pip [options]

ERROR: Invalid requirement: --no-cache-dir
pip: error: no such option: --no-cache-dir
```

**Comment by davidrpugh** [comment]
I commonly find myself needing to set `--no-cache-dir` for pip installs of `horovod` into conda environments. It would be great if I could specify this option directly in my `environment.yml` file.

**Comment by tarrade** [comment]
I am facing the same issue, pip change the version of some package installed in the conda section of the environment.yaml

```
  Attempting uninstall: httplib2
    Found existing installation: httplib2 0.18.1
    Uninstalling httplib2-0.18.1:
      Successfully uninstalled httplib2-0.18.1
Successfully ... httplib2-0.17.4
```

this is problematic since httplib2-0.17.4 had some issues. Didn't find any solution that could scale. Just look at the log to be sure no packages installed by conda got uninstall by pip.

how people deal with such dependency issue in production ?

**Comment by hadim** [comment]
I always end up installing pip deps manually after my environment has been setup with the --no-deps option.

That feature would be very convenient to have!!!

**Comment by floschne** [comment]
push

**Comment by NathanielRN** [comment]
This still seems to be broken in `4.9.2`. @kalefranz is there any chance of going with the syntax @sdvillal proposed? It looks like there are no more issues under the filter you posted regarding updates to these options.

**Comment by mummyhen** [comment]
An alternative is to set environment variable `PIP_NO_CACHE_DIR` to `1`:
```bash
export PIP_NO_CACHE_DIR=1
```

source: https://stackoverflow.com/a/60270281/8467558

**Comment by aragong** [comment]
Same issue in the latest version: 4.10.1. `--no-deps` option still raising an error... Is this feature still unachieved? or am I missing something? Achieve this feature will be really functional...

Thank you in advance!

````yml
name: base_py3.9
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - dask
  - black
  - bottleneck
  - rope
  - ipykernel
  - geojson
  - bs4
  - hypothesis
  - pre-commit
  - requests
  - numexpr
  - scipy
  - pytest
  - pylint
  - python=3.9
  - netcdf4
  - matplotlib
  - xarray
  - lxml
  - python-dotenv
  - flask
  - flit
  - pip
  - pip:
    - "git+https://github.com/IHCantabria/datahub.client@v0.8.6#egg=datahubClient --no-deps"
````

**Comment by alexcoca** [comment]
I would also like this feature. I am trying to install a github repository from master with code like 

```
- pip:
    - --editable=git+https://github.com/IHCantabria/datahub.client@v0.8.6#egg=datahubClient --src=.

```
and `--src` option is not recognised.

Unfortunately,


```
-pip
   - --editable=git+https://github.com/thu-coai/ConvLab-2.git@a83b8f108dce3f0f7bb801c7abe403423436458f#egg=Convlab-2 --install-option="--src=."
```

also does nothing.

Is it possible to achieve this at all with conda `4.9.2`?

**Comment by adamjstewart** [comment]
I would also like to see support for this. In my case, I'm trying to add `black>=21` to my pip list. However, since black has only ever had pre-releases, I need to use `pip install --pre 'black>=21'`. I've tried:
```yaml
dependencies:
  - pip:
    - --pre black>=21
```
but it doesn't seem to work.

**Comment by ihleonard-c3** [comment]
Being able to adjust the pip timeout (e.g. https://stackoverflow.com/questions/43298872/how-to-solve-readtimeouterror-httpsconnectionpoolhost-pypi-python-org-port) is another reason

**Comment by aragong** [comment]
this syntax is working fine for me:
```yaml
  - pip:
    - github_url@tag_version --install-option="--no-deps"
``` 

And the complete environment example maybe it is helpful for someone:
```yaml
name: teseo_apiprocess
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - dask
  - black
  - bottleneck
  - rope
  - ipykernel
  - geojson
  - bs4
  - hypothesis
  - pre-commit
  - requests
  - numexpr
  - scipy
  - pytest
  - pylint
  - python=3.9
  - netcdf4
  - matplotlib
  - xarray
  - lxml
  - python-dotenv
  - flask
  - flit
  - pytest-cov
  - pip
  - pre-commit
  - coverage-badge
  - openpyxl
  - xlrd
  - xlwt
  - flask-restx
  - geopandas
  - simplekml
  - pip:
    - git+https://github.com/IHCantabria/qualitas.downloader.git@v0.3.4 --install-option="--no-deps"
    - git+https://github.com/IHCantabria/datahub.client.git@v0.9.1 --install-option="--no-deps"
```
best regards!

**Comment by Sentewolf** [comment]
@aragong does this actually use the `--no-deps` option, or is the package installed with all its dependencies? I am unable to make the install-option work as described in https://github.com/conda/conda/issues/10807#issuecomment-996117363.

I find that using `--install-option` the package is installed, but the dependencies are too. I suspect that the `--install-option` parameter is not properly passed on to pip (but at least with this syntax pip and conda do not crash).

**Comment by aragong** [comment]
@Sentewolf you are totally right! Thank you for taking your time and comment!

We just change from the old `setup.py` to use `pyproject.toml` created with flit library and the dependencies are not declared in this new `pyproject.toml`, so pip is not reading the dependencies declared in the `requirements.txt`. And that's the point of my mistake, I was thinking that the extra command `--no-deps` was working well, but oh NO... it is not! F***!

I used to declare install-option to avoid pip to install all the requirements of the git package with pip. The mix of pip and conda libraries use to bring me environment incompatibilities, so I use to install with pip only the packages from git and the ones that are not available in conda.

Thank you very much to warn me about this. I hope conda fix this soon, and make available this syntax.

**Comment by luangtatipsy** [comment]
I faced this issue as well. In my case, I try to use `conda` in a Dockerfile. Instead of creating a new virtual env with
```sh
conda env create --file environment.yml
```
I decide to update the env that was automatically created and activated by default (`base`) with the following command.
```sh
conda env update -f environment.yml
```

Then I use the following command to install missing packages.
```sh
pip install --no-dependencies <package_name>
```

### System Requirements
- MacBook Pro (14-inch, 2021)
- Chip: Apple M1 Pro
- MacOS: 12.2.1 (21D62)

These are my files I mentioned earlier.
- `environment.yml`
```yaml
name: base
channels:
  - conda-forge
dependencies:
  - python=3.9
  - redis
  - influxdb
  - arrow
  - pika
  - Pillow
  - PyYAML
  - tqdm
  - matplotlib
  - scipy
  - scikit-learn
  - grpcio
  - protobuf
  - tensorflow
  # the following commands should work properly, but they don't.
  # - pip:
    # - opencv-python-headless --install-option="--no-deps"
    # - tensorflow-serving-api --install-option="--no-deps"
```
- Dockerfile
```dockerfile
FROM continuumio/miniconda3

COPY environment.yml .
RUN conda env update -f environment.yml
RUN pip install --no-dependencies tensorflow-serving-api opencv-python-headless

ENTRYPOINT ["python", "-c", \
            "import cv2; import tensorflow; import tensorflow_serving; print('success!')"]
```

With those files, I build and run a Docker image.
```sh
docker build -t example -f Dockerfile .
docker run example
```
The result looks like this
```
success!
```


I hope this helps :)
