### ISSUE TITLE
Integrate "features" into solver logic as "virtual" channels [discussion]

### ISSUE THREAD

**Issue by mbargull** [conda/conda#6950]
(@conda/conda-core)
This is something I had on my mind but didn't completely thought through, yet. So, no full-fledged proposal but just something I wanted to put up for discussion.

## Current state
As is, `features` don't integrate well into the solver's logic as their objectives are in competition with others, like channel prioritization or version maximization. Overly simplified, we currently have something like:
1. **requested packages: channel/version maximization**:
    for requested packages, choose their latest versions from the preferred channel,
2. **`feature` count minimization**:
    exclude new `feature` packages, if possible,
3. **`feature` package maximization**:
    exclude packages without existing `features`, if possible,
4. **other packages: channel/version maximization**:
    get latest version for remaining packages from the preferred channel.

Thus, we have an inconsistency between channel/version preference between requested (1.) and other (2.) packages, since 2. and 3. may exclude packages with higher channel priority or version due to `feature` usage.

## General idea
In contrast to these inconsistencies, we have the channel prioritization which integrates well and consistent with the other objectives. Hence my idea is that we could try to model `feature` optimization as channel prioritization to successfully integrate it with the other objectives.
To accomplish this, we can split a channel into "virtual" channels corresponding to their `features`.
As a pseudo example, take packages from `defaults[*]`, where `[*]` should mean "packages with any (or none) `features`". Then we can split those packages into virtual channels like:
```yaml
custom_multichannels:
  xxx:
    - defaults[avx]
    - defaults[]
    - defaults[openblas]
    - defaults[nomkl]
```
where `xxx` is the "channel" that poses as the solver's input and we express:
* "prefer AVX optimized builds, and, if none of those are available, take those without `features` (e.g. `mkl` variant of `numpy`), otherwise take `openblas` ones, and with least priority, use those with the `nomkl` feature"

Integrating this into step 4. above, we could replace step 3. by giving packages with desired `features` a higher priority.

To express step 2. above, we have to append the "virtual" channel corresponding to unused features at the end of the list, i.e.,
```yaml
custom_multichannels:
  xxx:
    - defaults[avx]
    - defaults[]
    - defaults[openblas]
    - defaults[nomkl]
    - defaults[*]
```
(to avoid duplication, instead of `[*]`, we can use "set difference ( `[*]` , set union ( `[avx]` , `[]` , `[openblas]` , `[nomkl]` )", of course.)

If we want to replicate step 1., i.e., ignore `features` for requested packages, we'd have to use `defaults[*]` as the channel. But to avoid that inconsistency we currently have with the `feature` optimization, we should rather use the same (virtual) channel list as for step 4.

## Equal priority "virtual"/`feature` channels
Currently, the channel prioritization does not allow channels with equal priority, apart from the case were the channel prioritization is completely turned off. We generally might want to have the possibility to assign equal priority to subsets of channels (easy enough to implement: just compare `(main_channel_prio, version, equi_channel_prio)` instead of  just`(main_channel_prio, version)`).
For those virtual/`feature` channels, we would want to express equality concerning features like
```yaml
custom_multichannels:
  xxx:
    - defaults[avx,fma]
    - defaults[]
    - defaults[openblas,nomkl]
    - defaults[*]
```
which could be translated to
```yaml
custom_multichannels:
  xxx:
    - - defaults[avx]
      - defaults[fma]
    - defaults[]
    - - defaults[openblas]
      - defaults[nomkl]
    - defaults[*]
```

## Multiple (real) channels
The examples above only used the single `defaults` channel. Currently, `features` are not bound to channels. Hence we want to be able to express take `feature` X from any channel, e.g., let's use `- *` to refer to "any channel" in the following:
```yaml
custom_multichannels:
  xxx:
    - *[avx,fma]
    - *[]
    - *[openblas,nomkl]
    - *[*]
```
. When we have `channels: [defaults, conda-forge]`, this may expand to 
```yaml
custom_multichannels:
  xxx:
    - defaults[avx,fma]
    - conda-forge[avx,fma]
    - defaults[]
    - conda-forge[]
    - defaults[openblas,nomkl]
    - conda-forge[openblas,nomkl]
    - defaults[*]
    - conda-forge[*]
```
and thus expanded again to
```yaml
custom_multichannels:
  xxx:
    - - defaults[avx]
      - defaults[fma]
    - - conda-forge[avx]
      - conda-forge[fma]
    - defaults[]
    - conda-forge[]
    - - defaults[openblas]
      - defaults[nomkl]
    - - conda-forge[openblas]
      - conda-forge[nomkl]
    - defaults[*]
    - conda-forge[*]
```

## misc
If the `[feature]` "subscript" makes sense, this could be added to the UI, e.g., to install the `openblas` variant of `numpy`, one could
```bash
conda install numpy[openblas]::numpy
```
or just
```bash
conda install [openblas]::numpy
```
\[EDIT\]
```bash
conda install 'numpy[features="openblas"]'
```
would be more in line with the match specification, I guess.
\[/EDIT\]

----
As said before, this idea isn't completely thought through, but just something that came to mind today. Hence it could very well be that I missed something very obvious that could easily nullify that concept...
