### ISSUE TITLE
conda fails to parse windows path in the channel list

### ISSUE THREAD

**Issue by cav71** [conda/conda#7006]
Hi,
this is a bug in parsing local repo dirs in the channel list.

This code in conda/common/url.py:
```
@memoize
def urlparse(url):
    if on_win and url.startswith('file:'):
        url.replace('\\', '/')
return parse_url(url)
```
Should be changed into:
```
@memoize
def urlparse(url):
    if on_win and url.startswith('file:'):
        url = url.replace('\\', '/')
return parse_url(url)
```

**Comment by goanpeca** [comment]
Thanks for the report @cav71, could you provide a series of steps to to get the test setup ready to reproduce the error?

**Comment by goanpeca** [comment]
@cav71 we need an example of the channel and how you entered it on the condarc file

You can use either

```yaml
channels:
  - defaults
  - C:\Users\user\develop\test_local_conda_channels\
ssl_verify: true
```

or
```yaml
channels:
  - defaults
  - file:///C:/Users/user/develop/test_local_conda_channels/
ssl_verify: true
```

And both are working correctly when running `conda info`.

Are you using? 

```yaml
channels:
  - defaults
  - file:\\\C:\Users\user\develop\test_local_conda_channels\
ssl_verify: true
```

If that is the case, that is [not a valid URI](https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/)
