### ISSUE TITLE
[Feature Request] Add support for package name aliasing

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#7552]
**I'm submitting a...**
  - [ ] bug report
  - [x] feature request

The basic requirement is to allow more than one package names for the same package. For example, there is a package called 'x-c' and it's github repo goes by the name 'libx' or 'xlib'. I want the users to get the same package, regardless of whether they do `conda install x-c` or `conda install xlib` or `conda install libx`. Right now, the simple way to do this is to have the recipe create multiple outputs and make one depend on the other, but that means two/three tarballs per release, which is inconvenient. It'd be great if one could specify something like:
```yaml
package: 
  name: {{ name }} 
  aliases:
      - {{ alias1 }}
      - {{ alias2 }}
  version: {{ version }}
```
This would inject into the metadata extra information, which would then be parsed by conda and make the solver think that there are three packages: name, alias1 and alias2 all with the same version.
