### ISSUE TITLE
"RuntimeError: dictionary changed size during iteration"

### ISSUE THREAD

**Issue by mithro** [conda/conda#7793]
When running the `conda render` command when rendering [conda-hdmi2usb-packages](https://github.com/mithro/conda-hdmi2usb-packages/tree/binutils-update). I'm getting the following traceback / error;

```
Traceback (most recent call last):
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/bin/conda-render", line 11, in <module>
    sys.exit(main())
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/cli/main_render.py", line 196, in main
    return execute(sys.argv[1:])
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/cli/main_render.py", line 176, in execute
    no_download_source=args.no_source)
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/api.py", line 44, in render
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/render.py", line 728, in render_recipe
    m = MetaData(recipe_dir, config=config)
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/metadata.py", line 853, in __init__
    self.parse_again(permit_undefined_jinja=True, allow_no_other_outputs=True)
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/metadata.py", line 941, in parse_again
    self.append_metadata_sections(append_sections_file, merge=True)
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/metadata.py", line 898, in append_metadata_sections
    raise_on_clobber=raise_on_clobber)
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/utils.py", line 1412, in merge_or_update_dict
    raise_on_clobber=raise_on_clobber)
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/utils.py", line 1412, in merge_or_update_dict
    raise_on_clobber=raise_on_clobber)
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/utils.py", line 1408, in merge_or_update_dict
    for key, value in new.items():
RuntimeError: dictionary changed size during iteration
```

An example meta.yaml file;
```yaml
package:
  name: flterm
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/timvideos/flterm.git

build:
  # y==GIT_DESCRIBE_NUMBER, z==DATE_NUM, x==GIT_DESCRIBE_HASH
  #
  # number: 10693001803050325
  #         1yyyy00zzzzzzzzzz
  number: {{ '1%04i00%s'|format(GIT_DESCRIBE_NUMBER|int, os.environ.get('DATE_NUM')) }}
  # string: 0693.20180305_0325.g588ce0e3
  #         yyyy.zzzzzzzz_zzzz.gxxxxxxxx
  string: {{ '%04i'|format(GIT_DESCRIBE_NUMBER|int) }}.{{ os.environ.get('DATE_STR') }}.{{ GIT_DESCRIBE_HASH }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
  {% for package in resolved_packages('host') %}
    - {{ package }}
  {% endfor %}
  {% for package in resolved_packages('build') %}
    - {{ package }}
  {% endfor %}

test:
  commands:
    - flterm --help

about:
  home: https://github.com/timvideos/flterm
  license: GPLv3
  summary: 'Serial boot program for MiSoC'
```

Conda environment configuration
```
add_anaconda_token: True
add_pip_as_python_dependency: True
aggressive_update_packages:
  - ca-certificates
  - certifi
  - openssl
allow_non_channel_urls: False
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: True
anaconda_upload: None
auto_update_conda: True
changeps1: False
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - mithro
  - timvideos
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  pkgs/main: https://repo.anaconda.com
  pkgs/free: https://repo.anaconda.com
  pkgs/r: https://repo.anaconda.com
  pkgs/pro: https://repo.anaconda.com
  tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld: file://
custom_multichannels:
  defaults: ["https://repo.anaconda.com/pkgs/main", "https://repo.anaconda.com/pkgs/free", "https://repo.anaconda.com/pkgs/r", "https://repo.anaconda.com/pkgs/pro"]
  local: ["file:///tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld"]
default_channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/free
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/pro
disallowed_packages: []
download_only: False
envs_dirs:
  - /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/envs
  - /home/travis/.conda/envs
force: False
json: False
local_repodata_ttl: 1
max_shlvl: 2
migrated_channel_aliases: []
no_dependencies: False
non_admin_enabled: True
notify_outdated_conda: True
offline: False
override_channels_enabled: True
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/pkgs
  - /home/travis/.conda/pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
report_errors: None
rollback_enabled: True
safety_checks: warn
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
use_index_cache: False
use_pip: True
verbosity: 0
whitelist_channels: []
```

Conda environment setup process;
```
+chmod a+x Miniconda3-latest-Linux-x86_64.sh
+'[' '!' -d /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda -o '!' -z true ']'
+./Miniconda3-latest-Linux-x86_64.sh -p /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda -b -f
PREFIX=/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda
installing: python-3.7.0-hc3d631a_0 ...
Python 3.7.0
installing: ca-certificates-2018.03.07-0 ...
installing: conda-env-2.6.0-1 ...
installing: libgcc-ng-8.2.0-hdf63c60_1 ...
installing: libstdcxx-ng-8.2.0-hdf63c60_1 ...
installing: libffi-3.2.1-hd88cf55_4 ...
installing: ncurses-6.1-hf484d3e_0 ...
installing: openssl-1.0.2p-h14c3975_0 ...
installing: xz-5.2.4-h14c3975_4 ...
installing: yaml-0.1.7-had09818_2 ...
installing: zlib-1.2.11-ha838bed_2 ...
installing: libedit-3.1.20170329-h6b74fdf_2 ...
installing: readline-7.0-h7b6447c_5 ...
installing: tk-8.6.8-hbc83047_0 ...
installing: sqlite-3.24.0-h84994c4_0 ...
installing: asn1crypto-0.24.0-py37_0 ...
installing: certifi-2018.8.24-py37_1 ...
installing: chardet-3.0.4-py37_1 ...
installing: idna-2.7-py37_0 ...
installing: pycosat-0.6.3-py37h14c3975_0 ...
installing: pycparser-2.18-py37_1 ...
installing: pysocks-1.6.8-py37_0 ...
installing: ruamel_yaml-0.15.46-py37h14c3975_0 ...
installing: six-1.11.0-py37_1 ...
installing: cffi-1.11.5-py37he75722e_1 ...
installing: setuptools-40.2.0-py37_0 ...
installing: cryptography-2.3.1-py37hc365091_0 ...
installing: wheel-0.31.1-py37_0 ...
installing: pip-10.0.1-py37_0 ...
installing: pyopenssl-18.0.0-py37_0 ...
installing: urllib3-1.23-py37_0 ...
installing: requests-2.19.1-py37_0 ...
installing: conda-4.5.11-py37_0 ...
installation finished.
+export PATH=/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/bin:/home/travis/bin:/home/travis/.local/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.9.1/bin:/home/travis/.kiex/elixirs/elixir-1.4.5/bin:/home/travis/.kiex/bin:/home/travis/.rvm/gems/ruby-2.4.1/bin:/home/travis/.rvm/gems/ruby-2.4.1@global/bin:/home/travis/.rvm/rubies/ruby-2.4.1/bin:/home/travis/gopath/bin:/usr/local/phantomjs/bin:/usr/local/phantomjs:/usr/local/neo4j-3.2.7/bin:/usr/local/maven-3.5.2/bin:/usr/local/cmake-3.9.2/bin:/usr/local/clang-5.0.0/bin:/home/travis/.gimme/versions/go1.7.4.linux.amd64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin:/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/bin:/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/bin:/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/bin
+PATH=/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/bin:/home/travis/bin:/home/travis/.local/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.9.1/bin:/home/travis/.kiex/elixirs/elixir-1.4.5/bin:/home/travis/.kiex/bin:/home/travis/.rvm/gems/ruby-2.4.1/bin:/home/travis/.rvm/gems/ruby-2.4.1@global/bin:/home/travis/.rvm/rubies/ruby-2.4.1/bin:/home/travis/gopath/bin:/usr/local/phantomjs/bin:/usr/local/phantomjs:/usr/local/neo4j-3.2.7/bin:/usr/local/maven-3.5.2/bin:/usr/local/cmake-3.9.2/bin:/usr/local/clang-5.0.0/bin:/home/travis/.gimme/versions/go1.7.4.linux.amd64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin:/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/bin:/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/bin:/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/bin
+conda update -y conda
Solving environment: ...working... done
# All requested packages already installed.
+'[' '!' -z '' ']'
+conda install -y conda-build
Solving environment: ...working... done
conda-build-3.15.1   | 459 KB    | ########## | 100% 
tqdm-4.26.0          | 59 KB     | ########## | 100% 
patchelf-0.9         | 68 KB     | ########## | 100% 
filelock-3.0.8       | 13 KB     | ########## | 100% 
psutil-5.4.7         | 305 KB    | ########## | 100% 
markupsafe-1.0       | 25 KB     | ########## | 100% 
pytz-2018.5          | 231 KB    | ########## | 100% 
jinja2-2.10          | 183 KB    | ########## | 100% 
glob2-0.6            | 17 KB     | ########## | 100% 
beautifulsoup4-4.6.3 | 138 KB    | ########## | 100% 
pkginfo-1.4.2        | 39 KB     | ########## | 100% 
pyyaml-3.13          | 177 KB    | ########## | 100% 
## Package Plan ##
  environment location: /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda
  added / updated specs: 
    - conda-build
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    conda-build-3.15.1         |           py37_0         459 KB
    tqdm-4.26.0                |   py37h28b3542_0          59 KB
    patchelf-0.9               |       hf484d3e_2          68 KB
    filelock-3.0.8             |           py37_0          13 KB
    psutil-5.4.7               |   py37h14c3975_0         305 KB
    markupsafe-1.0             |   py37h14c3975_1          25 KB
    pytz-2018.5                |           py37_0         231 KB
    jinja2-2.10                |           py37_0         183 KB
    glob2-0.6                  |           py37_0          17 KB
    beautifulsoup4-4.6.3       |           py37_0         138 KB
    pkginfo-1.4.2              |           py37_1          39 KB
    pyyaml-3.13                |   py37h14c3975_0         177 KB
    ------------------------------------------------------------
                                           Total:         1.7 MB
The following NEW packages will be INSTALLED:
    beautifulsoup4: 4.6.3-py37_0         
    conda-build:    3.15.1-py37_0        
    filelock:       3.0.8-py37_0         
    glob2:          0.6-py37_0           
    jinja2:         2.10-py37_0          
    markupsafe:     1.0-py37h14c3975_1   
    patchelf:       0.9-hf484d3e_2       
    pkginfo:        1.4.2-py37_1         
    psutil:         5.4.7-py37h14c3975_0 
    pytz:           2018.5-py37_0        
    pyyaml:         3.13-py37h14c3975_0  
    tqdm:           4.26.0-py37h28b3542_0
Downloading and Extracting Packages
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+conda install -y conda-verify
Solving environment: ...working... done
click-6.7            | 105 KB    | ########## | 100% 
conda-verify-3.1.0   | 32 KB     | ########## | 100% 
future-0.16.0        | 666 KB    | ########## | 100% 
## Package Plan ##
  environment location: /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda
  added / updated specs: 
    - conda-verify
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    click-6.7                  |           py37_0         105 KB
    conda-verify-3.1.0         |           py37_0          32 KB
    future-0.16.0              |           py37_0         666 KB
    ------------------------------------------------------------
                                           Total:         803 KB
The following NEW packages will be INSTALLED:
    click:        6.7-py37_0   
    conda-verify: 3.1.0-py37_0 
    future:       0.16.0-py37_0
Downloading and Extracting Packages
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+conda install -y anaconda-client
Solving environment: ...working... done
jupyter_core-4.4.0   | 63 KB     | ########## | 100% 
ipython_genutils-0.2 | 39 KB     | ########## | 100% 
python-dateutil-2.7. | 260 KB    | ########## | 100% 
nbformat-4.4.0       | 141 KB    | ########## | 100% 
jsonschema-2.6.0     | 62 KB     | ########## | 100% 
decorator-4.3.0      | 15 KB     | ########## | 100% 
clyent-1.2.2         | 18 KB     | ########## | 100% 
anaconda-client-1.7. | 140 KB    | ########## | 100% 
traitlets-4.3.2      | 133 KB    | ########## | 100% 
## Package Plan ##
  environment location: /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda
  added / updated specs: 
    - anaconda-client
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    jupyter_core-4.4.0         |           py37_0          63 KB
    ipython_genutils-0.2.0     |           py37_0          39 KB
    python-dateutil-2.7.3      |           py37_0         260 KB
    nbformat-4.4.0             |           py37_0         141 KB
    jsonschema-2.6.0           |           py37_0          62 KB
    decorator-4.3.0            |           py37_0          15 KB
    clyent-1.2.2               |           py37_1          18 KB
    anaconda-client-1.7.2      |           py37_0         140 KB
    traitlets-4.3.2            |           py37_0         133 KB
    ------------------------------------------------------------
                                           Total:         871 KB
The following NEW packages will be INSTALLED:
    anaconda-client:  1.7.2-py37_0
    clyent:           1.2.2-py37_1
    decorator:        4.3.0-py37_0
    ipython_genutils: 0.2.0-py37_0
    jsonschema:       2.6.0-py37_0
    jupyter_core:     4.4.0-py37_0
    nbformat:         4.4.0-py37_0
    python-dateutil:  2.7.3-py37_0
    traitlets:        4.3.2-py37_0
Downloading and Extracting Packages
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+conda install -y jinja2
Solving environment: ...working... done
# All requested packages already installed.
Solving environment: ...working... done
pexpect-4.6.0        | 77 KB     | ########## | 100% 
ptyprocess-0.6.0     | 23 KB     | ########## | 100% 
## Package Plan ##
  environment location: /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda
  added / updated specs: 
    - pexpect
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    pexpect-4.6.0              |           py37_0          77 KB
    ptyprocess-0.6.0           |           py37_0          23 KB
    ------------------------------------------------------------
                                           Total:          99 KB
The following NEW packages will be INSTALLED:
    pexpect:    4.6.0-py37_0
    ptyprocess: 0.6.0-py37_0
Downloading and Extracting Packages
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
```
