### ISSUE TITLE
"conda update package" does not update to latest version of package

### ISSUE THREAD

**Issue by j14r** [conda/conda#786]
If I build a package with the following minimal meta.yaml: 

``` yaml
package:
  name: some-package
  version: 1.0

build:
  number: 0
```

and do `conda install some-package` it gets installed correctly. Now i want to release a new version of my package with the additional dependency of twisted:

``` yaml
package:
  name: some-package
  version: 2.0

requirements:
  run:
    - twisted

build:
  number: 0
```

and do `conda update some-package` conda won't update some-package to the latest (2.0) version. If I do `conda update --all` it works fine and updates to version 2.0.

Is this a somehow intended behavior or a bug? Note that i did not specify a source section intentionally because i want to use this as a meta package. I also added my own channel and did not install it locally (what would imply --no-deps as I understand it).
