### ISSUE TITLE
Installing matplotlib-base from conda-forge lists matplotlib as installed from pip

### ISSUE THREAD

**Issue by mdeff** [conda/conda#7869]
Installing `matplotlib-base` from `conda-forge` lists `matplotlib` as installed from pip.

Steps to reproduce:
1. Install with `conda create -n test matplotlib-base`. My `.condarc` will only allow packages to be fetched from `conda-forge`, not `defaults`.
2. The environment exported with `conda env export -n test` contains the below.
   ```
   name: test
   channels:
     - conda-forge
   dependencies:
     - some-other-packages
     - matplotlib-base=3.0.0=py37hc039c98_2
     - some-other-packages
     - pip:
       - matplotlib==3.0.0
   ```

Initially posted as conda-forge/matplotlib-feedstock#182, redirected here by @ocefpaf.
