### ISSUE TITLE
Optional requirements?

### ISSUE THREAD

**Issue by jsw-fnal** [conda/conda#793]
Sounds like an oxymoron.  I started thinking about this just now when I did `conda install matplotlib`.  I'm planning to use matplotlib exclusively in the IPython notebook, so I won't be using the Qt backend for matplotlib.  However, Qt is installed because it is a dependency of matplotlib.  Since Qt is so large, downloading the package took the bulk of the total install time.

Is there a way to mark that some dependencies will only be needed by some users?  I'm not sure I can think of a good way to handle this sort of situation.  Maybe a separate package called `matplotlib-Qtbackend` would be sufficient, but then some users will be quite surprised to find that installing matplotlib and Qt is not sufficient to get them a Qt backend.  What if the matplotlib and Qt packages both knew to look for the other when they were installed, and if both are present, to install the backend package?

I'm just brainstorming.

**Comment by cdeil** [comment]
I have a conda package that depends only on a few things, but I want to package it so that users get some important optional dependencies by default as well.

In Debian this is possible with the "recommends" list
https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html#s-depends
and the user has to explicitly say `--no-install-recommends` to deselect those.

@asmeurer – You're saying this should be done by creating a separate conda metapackage?
I.e. in my case I'd create a meta-package `gammapy-all` that includes `gammapy` as well as optional dependencies like `scipy`, `matplotlib`, ...?

**Comment by cdeil** [comment]
pip also has this feature ... there it's called "extras":
http://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

If the recommended solution for this remains to create meta-packages, can this be added to the conda docs? (I couldn't find something useful with Google)

**Comment by asmeurer** [comment]
Look at, for instance, how `blaze` vs. `blaze-core` work (`conda info blaze`/`conda info blaze-core`).

**Comment by janssen** [comment]
It would be great to have the matplotllib recipe drop the dependency on Qt.  I use matplotlib purely with the agg backend, and I use it with Kivy.  Neither use of it requires Qt, but I still get Qt when I specify matplotlib as a dependency in conda recipes.  I have to go through and delete all the Qt stuff after the env is built.  I think there should be a 'matplotlib' package, and a 'matplotlib-with-Qt' metapackage.

**Comment by dhirschfeld** [comment]
I think there's a reasonable overhead in specifying a new yaml and building a new package for each set of optional dependencies - yes it can work but I think it would be much easier to specify in the same yaml as the required dependencies IMHO.

My suggestion would be to allow optional dependencies to simply be labelled sections under the build or run requirements. The labelled sections then specify the dependencies for that label - e.g. for the hypothetical meta.yaml below:
```yaml
package:
  name: mypackage
  version: 1.0.0

  requirements:
    build:
      - python

    run:
      - python
      - numpy

      pyqt:
        - pyqt

      docs:
        - sphinx
        - numpydoc >= 0.5.0

      test:
        - nose
        - mock
```

Only python and numpy would get installed with:
```
conda install mypackage
```
to install all the optional deps you would use
```
conda install mypackage[all]
```
...which would be equivalent to
```
conda install mypackage[pyqt, docs, test]
```
To install mypackage with just the pyqt dependency would be
```
conda install mypackage[pyqt]
```

Conveniently this would also solve my own issue (https://github.com/conda/conda/issues/1665) where I want to be able to independently install the test deps.

**Comment by msarahan** [comment]
Fwiw, I really like this syntax.

**Comment by mcg1969** [comment]
I think something like this is a good idea. However, it's important to note that it depends on the underlying package being able to gracefully handle the different combinations of dependencies. It's also similar in execution to our `with_features_depends` system.

**Comment by JanSchulz** [comment]
IMO, this syntax `conda install mypackage[all]` is not a good idea as it is very python specific. It also doesn't address all issues:

* You need to be able to add files to specific packages (matplotlib might build a qt backed, but this backend should be in a different package).
* The above example assumes that the package is build at install time (at least if sphinx is used as a requirement for the docs package), but that doesn't work -> it needs to be installed for the build and the docs probably do not have any run requirements.

I would find it better if there is an additional way to add binary packages, which can take specific files and the rest is taken by the main package. Like:

```
package:
  name: mypackage
  version: 1.0.0

  requirements:
    build:
     # build requirements are for all packages...
      - python

    run:
      - python
      - numpy

binary-package:
  name: mypackage-pyqt
  requirements:
        - pyqt
  files:
        include: 
          - pyqt/*.*
        exclude:
          - pyqt/README.md

binary-package:
  name: mypackage-docs
  requirements:
       # none?
  files:
        include: 
          - docs/*.*
        exclude:
          - docs/README.md

binary-package:
  name: mypackage-tests
  requirements:
       - nose
       - mock
  files:
        include: 
          - src/matplotlib/tests
```

This would build 4 packages: mypackage-tests, mypackage-docs, mypackage-pyqt and mypackage. Each package can be installed as before...

Se also the debian dir for the matplotlib debian package, which works similar, only the above info is split across multiple files: https://anonscm.debian.org/cgit/python-modules/packages/matplotlib.git/tree/debian

- `control` defines the packages and their dependencies
- `*.install` tells the build process, which files belong to which package
