### ISSUE TITLE
Add GIT_BUILD_NUMBER to meta.yaml

### ISSUE THREAD

**Issue by srossross** [conda/conda#826]
For source builds it would be great to sync the build #'s between binstar build and other build sources currently in our wakari recipes ([see tty.js](https://github.com/ContinuumIO/tty.js/blob/master/conda.recipe/meta.yaml#L6) as an example) we use `environ.get('BINSTAR_BUILD', 1)` It would be great if we provided a git-based solution using `git describe` ([like this issue states](https://github.com/Binstar/binstar.org/issues/68#issuecomment-43923025))

Perhaps the syntax could look like:

``` yaml
package:
  name: tty.js 
  version: {{latest_git_tag()}}

build:
  number: {{commits_since_latest_git_tag()}}

```

cc @tswicegood @asmeurer
