### ISSUE TITLE
AssertionError in resolve module from not adding dependencies on strictness == 3

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#918]
See https://github.com/conda/conda-build/issues/205. When the strictness of a package is 3, the dependencies are not added. This can lead to issues if not all the dependencies of that package are specified. At the very least, the error message should be improved. 

The strictness check was removed at https://github.com/conda/conda/commit/3077dc15d2da7b33b512ad087181bd96e98f6b10 but reverted at https://github.com/conda/conda/commit/c4c844be32c83a2a3a7013034a97cbed9f8fa84b because it caused some serious performance regressions, because the larger number of packages created a much larger version equation with many more nonzero terms for the SAT solver.

**Comment by pelson** [comment]
Might be worth re-visiting this in the light of #1702

**Comment by mcg1969** [comment]
Agreed. I saw this when working on 1702. I do not understand the logic and think it should be fixed.

**Comment by rekcahpassyla** [comment]
Another vote for a fix for this if possible- we have quite a complicated package structure where we want to have packages defined similar to the below:

### Case 1
Package `common1_x 0.1.0`
```
requirements:
    build:
       - python
       - numpy >=1.9
       - pandas >=0.15.2
       - setuptools

    run:
       - python
       - numpy >=1.9
       - pandas >=0.15.2
       - nose
       - coverage
```

Package `common2_x 0.2.0`
```
requirements:
    build:
       - python
       - numpy >=1.9
       - pandas >=0.15.2
       - setuptools

    run:
       - python
       - numpy >=1.9
       - pandas >=0.15.2
       - common1_x
```

Package `toplevel_x 1.0.0`
```
requirements:
    build:
       - python

    run:
       - python             2.7*
       - numpy              1.9.2                   py27_0
       - pandas             0.15.2                  np19py27_1
       - common1_x          0.1.0                   py27_0
       - common2_x          0.2.0                   py27_0
```

If the above are built and put in a conda repository, the following error is observed (at the end of the stack trace)

```
$ conda create -p c:\condatest\envs\toplevel -c thechannel toplevel_x==1.0.0
Fetching package metadata: ..........
Solving package specifications: ..........An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

...
  File "C:\dev\bin\Anaconda\lib\site-packages\conda\resolve.py", line 624, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: pandas-0.15.2-np19py27_1.tar.bz2 MatchSpec(u'python-dateutil 2.4.1')
```


### Case 2
Package `common1_y 0.1.0`
```
requirements:
    build:
       - python
       - numpy >=1.9
       - pandas >=0.15.2
       - setuptools

    run:
       - python
       - numpy              1.9.2                   py27_0
       - pandas             0.15.2                  np19py27_1
       - python-dateutil    2.4.1                   py27_0
       - pytz               2015.4                  py27_0
       - six                1.9.0                   py27_0
       - coverage           3.7.1                   py27_0
       - nose               1.3.7                   py27_0
```

Package `common2_y 0.2.0`
```
requirements:
    build:
       - python
       - numpy >=1.9
       - pandas >=0.15.2
       - setuptools

    run:
       - python
       - common1_y          0.1.0                   np19py27_0
```

Package `toplevel_y 1.0.0`
```
requirements:
    build:
       - python

    run:
       - python             2.7*
       - numpy              1.9.2                   py27_0
       - pandas             0.15.2                  np19py27_1
       - common2_y          0.2.0                   py27_0
```

```
$ conda create -p c:\condatest\envs\toplevel -c thechannel toplevel_y==1.0.0
Fetching package metadata: ..........
Solving package specifications: .........An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues
...
  File "C:\dev\bin\Anaconda\lib\site-packages\conda\resolve.py", line 624, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: pandas-0.15.2-np19py27_1.tar.bz2 MatchSpec(u'python-dateutil 2.4.1')
```

According to the current behaviour, our `toplevel` package `meta.yaml` currently needs to look like the following, with every dependency of every subpackage specified. It gets rapidly unworkable as we may have hierarchies 4 levels deep. 

```
requirements:
    build:
       - python

    run:
       - python             2.7*
       - numpy              1.9.2                   py27_0
       - pandas             0.15.2                  np19py27_1
       - common1            0.1.0                   py27_0
       - common2            0.2.0                   py27_0
       # pandas dependencies
       - python-dateutil    2.4.1                   py27_0
       - pytz               2015.4                  py27_0
       - six                1.9.0                   py27_0
       # common1 dependencies
       - coverage           3.7.1                   py27_0
       - nose               1.3.7                   py27_0

```

Output of `conda info`:

```
$ conda info
Current conda install:

             platform : win-64
        conda version : 3.18.3
  conda-build version : 1.13.0+451.g76ab604
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : C:\dev\bin\Anaconda  (writable)
  default environment : C:\dev\bin\Anaconda
     envs directories : C:\dev\bin\Anaconda\envs
        package cache : C:\dev\bin\Anaconda\pkgs
         channel URLs : 
                        http://repo.continuum.io/pkgs/dev/win-64/
                        http://repo.continuum.io/pkgs/dev/noarch/
                        http://repo.continuum.io/pkgs/gpl/win-64/
                        http://repo.continuum.io/pkgs/gpl/noarch/
                        http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/free/noarch/
          config file : 
    is foreign system : False
```
