### ISSUE TITLE
Impossible to create env in multi user mode miniconda through ansible

### ISSUE THREAD

**Issue by TcaManager** [conda/conda#9302]
### Steps to Reproduce

An ansible role that runs the following tasks

- Add a user with bash shell
- Touch the .bashrc file with 0744 permissions
- Insert line unset SUDO_UID SUDO_GID SUDO_USER in the .bashrc file
- Runs command conda init bash as the created user
- Runs source .bashrc && conda create --prefix command in subdirectory of the user home

```
- name: 'Add the user {{app_user}} with a bash shell'
  user:
    name: '{{app_user}}'
    shell: /bin/bash

- name: 'Touch {{app_user_home}}/.bashrc file'
  file:
    path: '{{app_user_home}}/.bashrc'
    state: touch
    mode: '0744'
    owner: '{{app_user}}'
    group: '{{app_user}}'

- name: Insert a line at the beginning of {{app_user_home}}/.bashrc file.
  lineinfile:
    path: '{{app_user_home}}/.bashrc'
    line: 'unset SUDO_UID SUDO_GID SUDO_USER'

- name: 'Init Miniconda for user {{app_user}}'
  shell: '{{ miniconda_conda_bin }} init bash'
  args:
    chdir: '{{app_user_home}}'
  become: yes
  become_user: '{{app_user}}'

- name: 'Recursively change owunset SUDO_UID SUDO_GID SUDO_USERnership of {{app_user_home}} directory'
  file:
    path: '{{app_user_home}}'
    state: directory
    recurse: yes
    owner: '{{app_user}}'
    group: '{{app_user}}'

- name: 'Create environment in {{ app_environment_prefix }}'
  shell: 'source {{app_user_home}}/.bashrc && {{ miniconda_conda_bin }} create --yes --quiet --prefix {{ app_environment_prefix }} --file {{ app_environment_python_requirements }} python={{ app_environment_python_version }}'
  args:
    chdir: '{{app_user_home}}'
  become: yes
  become_user: '{{app_user}}'
```

## Expected Behavior

Every step runs perfectly except the last one, I get the message

```
NotWritableError: The current user does not have write permissions to a required path.
path: /home/proxirhmanager/.conda/pkgs/urls.txt
```

I don't get how ansible could run the conda command with sudo, miniconda is installed in /opt/miniconda in multi user mode.
See the ansible output below

```
    TASK [install-python-application-from-git : Create environment in /home/proxirhmanager] ***
    fatal: [instance]: FAILED! => {"changed": true, "cmd": "source /home/proxirhmanager/.bashrc && /opt/miniconda/bin/conda create --yes --quiet --prefix /home/proxirhmanager --file /home/proxirhmanager/app/requirements.txt python=3.7", "delta": "0:00:02.762064", "end": "2019-10-02 10:47:41.790826", "msg": "non-zero return code", "rc": 1, "start": "2019-10-02 10:47:39.028762", "stderr": "\nNotWritableError: The current user does not have write permissions to a required path.\n  path: /home/proxirhmanager/.conda/pkgs/urls.txt\n  uid: 1000\n  gid: 1000\n\nIf you feel that permissions on this path are set incorrectly, you can manually\nchange them by executing\n\n  $ sudo chown 1000:1000 /home/proxirhmanager/.conda/pkgs/urls.txt\n\nIn general, it's not advisable to use 'sudo conda'.", "stderr_lines": ["", "NotWritableError: The current user does not have write permissions to a required path.", "  path: /home/proxirhmanager/.conda/pkgs/urls.txt", "  uid: 1000", "  gid: 1000", "", "If you feel that permissions on this path are set incorrectly, you can manually", "change them by executing", "", "  $ sudo chown 1000:1000 /home/proxirhmanager/.conda/pkgs/urls.txt", "", "In general, it's not advisable to use 'sudo conda'."], "stdout": "Collecting package metadata (current_repodata.json): ...working... failed", "stdout_lines": ["Collecting package metadata (current_repodata.json): ...working... failed"]}

```

**Comment by soapy1** [comment]
hmm, how did you install miniconda? I would expect if you executed that task as the app user this problem should not appear?

I think the easiest thing to do here is force the .conda dir to be writable by the app user. Something like:
```
- name: Ensure .conda is writable by {{ app_user }}
  file:
    path: "{{app_user_home}}/.conda/pkgs"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
```
