### ISSUE TITLE
Allow Channel Overrides with Strict Channel Priority

### ISSUE THREAD

**Issue by alanhdu** [conda/conda#9642]
Right now, I don't think you can combine channel override sin an `environment.yml` with `channel_priority: strict`. If I try to create an environment using

```yaml
name: scratch
channels:
- pytorch
- conda-forge
- defaults
dependencies:
  - pytorch=1.4
  - cpuonly=1.
  - python=3.6
  # lower channel priority, but I want to explicitly override
  - defaults::mkl=2019.4
```

then I get an `UnsatisfiableError`. But if I set `channel_priority: false`, then I can install this correctly.
