### ISSUE TITLE
Cmake fails the "CheckIncludeFile" check because of an extra ";"

### ISSUE THREAD

**Issue by GuillaumeHolley** [conda/conda#9741]
Hi there,

So I have been intending since a few days to build a recipe for a package and when trying out `conda build mypackage`, it's been systematically failing. The short story is that `build.sh` calls Cmake and Cmake seems to fail one of his check because of an extra `;` lying around. Maybe I'm really wrong about this but check for yourself.

My `build.sh` looks like this:
```
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${PREFIX} ..
make && make install
``` 
The call to Cmake fails on this:
```
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: $BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-cc
-- Check for working C compiler: $BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: $BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-c++
-- Check for working CXX compiler: $BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Release mode
-- Looking for pthread.h
-- Looking for pthread.h - not found
CMake Error at /home/username/miniconda3/conda-bld/mypackage_1583621943006/_build_env/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /home/username/miniconda3/conda-bld/mypackage_1583621943006/_build_env/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /home/username/miniconda3/conda-bld/mypackage_1583621943006/_build_env/share/cmake-3.16/Modules/FindThreads.cmake:220 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:21 (find_package)
```

He took me a while to realize that the real issue is not with finding the pthread header. After digging into the file `$SRC_DIR/build/CMakeFiles/CMakeError.log`, I obtained:
```
Determining if the include file pthread.h exists failed with the following output:
Change Dir: /home/username/miniconda3/conda-bld/mypackage_1583621943006/work/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_623cb/fast && /usr/bin/make -f CMakeFiles/cmTC_623cb.dir/build.make CMakeFiles/cmTC_623cb.dir/build
make[1]: Entering directory '/home/username/miniconda3/conda-bld/mypackage_1583621943006/work/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_623cb.dir/CheckIncludeFile.c.o
/home/username/miniconda3/conda-bld/mypackage_1583621943006/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc   -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/username/miniconda3/include;-std=c11 -march=native    -o CMakeFiles/cmTC_623cb.dir/CheckIncludeFile.c.o   -c /home/username/miniconda3/conda-bld/mypackage_1583621943006/work/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
x86_64-conda_cos6-linux-gnu-cc: fatal error: no input files
compilation terminated.
/bin/sh: 1: -std=c11: not found
CMakeFiles/cmTC_623cb.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_623cb.dir/CheckIncludeFile.c.o' failed
make[1]: *** [CMakeFiles/cmTC_623cb.dir/CheckIncludeFile.c.o] Error 127
make[1]: Leaving directory '/home/username/miniconda3/conda-bld/mypackage_1583621943006/work/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_623cb/fast' failed
make: *** [cmTC_623cb/fast] Error 2
```

Now, GCC tells me it cannot compile the test file because no input file is provided. But if we zoom on the call to GCC, there is `-isystem /home/username/miniconda3/include;`. I'm no GCC/Bash specialist but I think the `;` at the end of this substring is invalid syntax here: it forces the GCC command to stop after the `;` and everything after is interpreted as a new command (hence the `/bin/sh: 1: -std=c11: not found`).

Any thoughts on this? Thank you for the help.

Guillaume

PS: I'm running a brand new install of conda 4.8.2, installed with miniconda3.

**Comment by winni2k** [comment]
Can you share your `meta.yaml` file as well?

**Comment by GuillaumeHolley** [comment]
Sure. Here you go (I have redacted a few things):
```
{% set version = "1.0" %}
{% set sha256 = "e67ed5bfce20281b746e4e3dda0b93881affc2add9b23fd940b4c44354de5073" %}

package:
  name: mypackage
  version: '{{version}}'

source:
  url: file:////path/to/mypackage.zip
  sha256: '{{sha256}}'

build:
  number: 0
  skip: true # [win]

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
    - cmake >=2.8.12
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - mypackage

about:
  home: https://blabla.com
  license: BSD-2
  license_file: LICENSE
  license_family: BSD
  summary: blabla
```

**Comment by GuillaumeHolley** [comment]
I would like to try having the whole thing using Cmake >= 3.5. I have modified my `meta.yaml` like this:
```
requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
    - cmake >=3.5.0
  host:
    - zlib
    - cmake >=3.5.0
  run:
    - zlib
```

Yet, each call to `conda build mypackage` install and uses cmake 3.16.4... Am I missing something here?

Thanks,
Guillaume
