### ISSUE TITLE
Multiple constraints on the same package result in package becoming a requirement

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda#9956]
If a package has multiple constraints on a package of the same name, in addition to apply the constrains conda also introduces the constrained package as a requirement.  

For example for package created from the following recipe which is available on the `jjhelmus` channel:

``` yaml
package:
  name: cbug
  version: 1.0.0
build:
  noarch: true
requirements:
  run_constrained:
    - xz !=5.2.3
    - xz !=5.2.5
```

Creating an environment with this package unnecessarily pulls in a compatible xz package:

```
$ conda create -n example -c defaults -c jjhelmus cbug=1 --dry-run
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/jhelmus/conda/envs/example

  added / updated specs:
    - cbug


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cbug-1.0.0                 |                0           3 KB  jjhelmus
    ------------------------------------------------------------
                                           Total:           3 KB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  cbug               jjhelmus/noarch::cbug-1.0.0-0
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  xz                 pkgs/main/linux-64::xz-5.2.4-h14c3975_4



DryRunExit: Dry run. Exiting.
```

A work around seem to be to combine similar constraints into a single entry.  For example:

``` yaml
package:
  name: cbug
  version: 2.0.0
build:
  noarch: true
requirements:
  run_constrained:
    - xz !=5.2.3,!=5.2.5
```

```
$ conda create -n example -c defaults -c jjhelmus cbug=2 --dry-run
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/jhelmus/conda/envs/example

  added / updated specs:
    - cbug=2


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cbug-2.0.0                 |                0           3 KB  jjhelmus
    ------------------------------------------------------------
                                           Total:           3 KB

The following NEW packages will be INSTALLED:

  cbug               jjhelmus/noarch::cbug-2.0.0-0



DryRunExit: Dry run. Exiting.
```
