### ISSUE TITLE
environment.yml: channel-name::package-name syntax has global effect 

### ISSUE THREAD

**Issue by w-hc** [conda/conda#9993]
conda version 4.8.3

When I create the following environment.yml
```yml
name: temp
channels:
  - defaults
dependencies:
  - python=3
  - numpy
  - conda-forge::av
  - jupyterlab=2.1.4
```
I expect that ```conda-forge::av``` would only introduce conda-forge channel to that single package. Other dependencies should not be able to access anything from ```conda-forge```.
Currently ``` jupyterlab=2.1.4``` is not available in the default channel, and so I expect the installation to fail.
In reality however conda would go ahead to fetch ``` jupyterlab=2.1.4``` from conda-forge, without notifying me what happened. 

I also tried this 
```yml
name: temp
channels:
  - defaults
dependencies:
  - python=3
  - numpy
  - jupyterlab=2.1.4
```
In this case, ```conda-forge``` does not appear anywhere, and the installation fails as it should.

The desired behavior should be to isolate the effect of the channel specifier to the single line, not exposing it globally.
